### ISSUE TITLE
运行时高CPU占用，无法访问网络

### ISSUE THREAD

**Issue by Akane195** [mellow-io/mellow#105]
### 使用操作系统类型以及版本
win10 workstation 1909

### 使用 Mellow 版本
0.1.11

### 问题描述
CPU占用95% 无法访问网络

### 相关配置
```
[Endpoint]
Proxy, ss, ss://chacha20-ietf:1*******@*********:*****
Direct, builtin, freedom, domainStrategy=UseIP
Dns-Out, builtin, dns

[RoutingRule]
IP-CIDR, 192.168.1.0/24, Proxy
FINAL, Direct

[Dns]
hijack = Dns-Out

[DnsServer]
localhost

```

### 相关日志

[log.log](https://github.com/mellow-io/mellow/files/3964995/log.log)

**Comment by eycorsican** [comment]
https://github.com/mellow-io/mellow/issues/87
