### ISSUE TITLE
加入脚本执行机制

### ISSUE THREAD

**Issue by eycorsican** [mellow-io/mellow#106]
允许在连接前、连接后、断开连接后等时间点，执行一些脚本程序。

因为 Mellow 本身所支持的代理协议可能并不满足所有人的需求，它本身的 Shadowsocks 可能也存在着一些问题（ https://github.com/mellow-io/mellow/issues/90 https://github.com/mellow-io/mellow/issues/80 ），但 Mellow 的全局透明特性又是其它代理工具所不具备的，所以不少用户将 Mellow 配合不同的代理软件一起使用。加入脚本执行机制后，用户就可以把另一个代理软件的连接和关闭操作自动化，省去繁琐的步骤，也可以解决如 https://github.com/mellow-io/mellow/issues/76 这样的需求。

**Comment by Vigilans** [comment]
I'd like to implement this feature recently...

**Comment by felixding** [comment]
这个功能非常实用，可以极大地增加扩展性。期待。
