### ISSUE TITLE
Source code for latency load balancer

### ISSUE THREAD

**Issue by lewisxy** [mellow-io/mellow#108]
I cannot find any source code or documentation related to latency load balancer (`"strategy": "latency"` in `"balancer"`) in [v2ray project](https://github.com/v2ray/v2ray-core/). Can you provide the source code for this? Thanks.

**Comment by adwinb** [comment]
@lewisxy  There is a [pull request](https://github.com/v2ray/v2ray-core/pull/1924) about this in v2ray project.
