### ISSUE TITLE
ICMP协议的ping包不能通过mellow

### ISSUE THREAD

**Issue by thesunfei** [mellow-io/mellow#114]
### 使用操作系统类型以及版本

Windows 10

### 使用 Mellow 版本

0.1.11

### 问题描述

网络代理访问正常，但ping任何公网ip都无响应。

### 相关配置

{
  "outbounds": [{
      "protocol": "freedom",
      "tag": "Direct",
      "settings": {
        "domainStrategy": "UseIP"
      }
    },
    {
      "tag": "Socks-Out",
      "protocol": "socks",
      "settings": {
        "servers": [{
          "address": "127.0.0.1",
          "port": 1000
        }]
      }
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "outboundTag": "Direct",
        "ip": [
          "geoip:private",
          "服务器IP"
        ]
      },
      {
        "type": "field",
        "outboundTag": "Socks-Out",
        "network": "tcp,udp,icmp"
      }
    ]
  }
}

**Comment by reason211** [comment]
socks5 不大好用，换个连接方式吧，比如vmess。
之前纠结socks5 纠结了好几天，后来换成vmess，从服务端到客户端，1个小时就整好了。
感觉mellow 更亲近vmess协议 😅

**Comment by FH0** [comment]
这是因为socks5不支持icmp，代理icmp，需要纯vpn的软件，比如openvpn,wireguard,pptp

**Comment by eycorsican** [comment]
原包不通过，但会做重新发包
