### ISSUE TITLE
MacOS菜单栏中点Mellow图标下拉菜单均变灰不可用

### ISSUE THREAD

**Issue by adrianzhang** [mellow-io/mellow#117]
### 使用操作系统类型以及版本
MacOS El Capitan 10.11.6

### 使用 Mellow 版本
0.1.11

### 问题描述
最早第一次安装后可以使用，建立了config如图。![图片](https://www.basiy.com/img/mellow.png)
今天增加了一个config，修改后，从Mellow菜单选择Config Folder进入目录，将增加的这个config修改了一点，然后改名，Mellow开始出现如图的各个菜单都变灰。
1) 杀进程，重启Mellow，无效
2) 重启电脑（Mellow之前设置为随系统启动），无效
3) 将改名后的文件删除后，重复以上两步，都无效
4) 重装Mellow，无效
问题是从配置文件改名开始出现，无法修复。 

### 相关配置
确认可用配置

### 相关日志
日志无法从菜单中选择查看

**Comment by adrianzhang** [comment]
补充细节：

在变灰前，config选择的是未改名前的新增config

用Appclean完全卸载Mellow后再重装，菜单变得可用了。需要重新写配置。

**Comment by eycorsican** [comment]
点 Dock 上的图标看窗口错误信息
