### ISSUE TITLE
是否支持DOH/DOHL

### ISSUE THREAD

**Issue by Eintler** [mellow-io/mellow#121]
### 使用操作系统类型以及版本

macOS 10.15.3 

### 使用 Mellow 版本
v0.1.11

### 问题描述
是否支持DOH和DOHL

### 相关配置
"dns": {
    "servers": [
      "https+local://1.1.1.1/dns-query",
      "1.1.1.1",
      "localhost",
      "8.8.8.8"
    ]
  }

### 相关日志
开启如上配置时,不能启动mellow

**Comment by H0u5er** [comment]
遇到同样的问题，强制退出Mellow后，导致Homebrew无法正常运行v2ray-core

希望Mellow提供查询当前v2ray-core版本

**Comment by eycorsican** [comment]
不支持
