### ISSUE TITLE
README.md中GeoLite2-Country.tar.gz的下载地址失效

### ISSUE THREAD

**Issue by yixy** [mellow-io/mellow#124]
### 问题描述

 README.md 文档 “**可以在 Linux 上以命令行方式运行吗？**” 小节中 [GeoLite2-Country.tar.gz的下载地址](http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz)好像已失效。

目前需要注册账户登录后下载，下载页面如下，可以在README里更新下说明

https://dev.maxmind.com/geoip/geoip2/geolite2/

谢谢！

**Comment by mzxwt** [comment]
现在需要注册后获取AccountID和LicenseKey才可以下载。macOS下可使用Homebrew里的geoipupdate，在GeoIP.config内配置后可自动下载GeoLite2。Linux下可根据MaxMind的Guideline设置。
