### ISSUE TITLE
能否添加对Trojan协议的支持

### ISSUE THREAD

**Issue by wesleyxie** [mellow-io/mellow#125]
### 使用操作系统类型以及版本
MACOS

### 使用 Mellow 版本
v.0.1.11

### 问题描述
能否添加对Trojan协议的支持

### 相关配置
N/A

**Comment by lazytiger** [comment]
用trojan客户端然后在mellow里配置socks是可以工作的

**Comment by jhjhdda** [comment]
您好，我是用trojan的，请问以下配置可以么(如果方便的话劳烦帮忙给出修正，谢谢）我trojan指向127.0.0.1：1080
[Endpoint]
Socks-Out, builtin, socks, address=127.0.0.1, port=1080, user=, pass=
Dns-Out, builtin, dns

[RoutingRule]
DOMAIN-KEYWORD, geosite:cn, Direct
GEOIP, cn, Direct
GEOIP, private, Direct
FINAL, MyProxyServer

[Dns]
hijack = Dns-Out

[DnsServer]
localhost
8.8.8.8

**Comment by lazytiger** [comment]
`Endpoint]
MyProxyServer, builtin, socks, address=127.0.0.1, port=1080
Direct, builtin, freedom, domainStrategy=UseIP
Dns-Out, builtin, dns

[RoutingRule]
DOMAIN-KEYWORD, geosite:cn, Direct
DOMAIN-FULL, 你的trojan域名, Direct
GEOIP, cn, Direct
GEOIP, private, Direct
FINAL, MyProxyServer

[Dns]
hijack = Dns-Out

[DnsServer]
localhost
8.8.8.8`
试一下这个配置行不行

简单解释一下你的配置存在的问题
1、Socks-Out这是一个tag，也即名字，必须跟你路由里用的一致
2、你没有设置Direct这个tag
3、你需要把你的trojan的域名给Direct出去

**Comment by jhjhdda** [comment]
可以了，谢谢

**Comment by kioneg-lau** [comment]
多谢

**Comment by wangyuyong** [comment]
您好，我按上面的配置连接了trojan，但trojan客户端一直报ssl handshake的错误。我给浏览器设置代理是可以正常上网的，但用mellow就不行了

**Comment by paomuer** [comment]
您好 我也碰到如上问题，trojan 的日志 一直是 SSL handshake failed with  ip:port  Operation canceled
不然就是 stream truncated
