### ISSUE TITLE
Core 程序会开源吗？

### ISSUE THREAD

**Issue by THaGKI9** [mellow-io/mellow#130]
有时候遇到一些问题想自己查一下源码，发现 core 并没有开源，请问有开源的计划吗？

**Comment by fbion** [comment]
https://github.com/eycorsican/go-tun2socks

**Comment by THaGKI9** [comment]
mellow的core虽然是基于tun2socks但是还是有不同的呀

________________________________

**Comment by fbion** [comment]
https://github.com/FlowerWrong/tun2socks

**Comment by fbion** [comment]
core --help
