### ISSUE TITLE
mellow是否有计划支持v2ray-plugin插件？

### ISSUE THREAD

**Issue by shiraha777** [mellow-io/mellow#133]
### 使用操作系统类型以及版本
Windows 10 LTSC 1903

### 使用 Mellow 版本
v0.1.11

### 问题描述
在翻阅配置文件示例后发现似乎没有对ss的第三方SIP002插件的支持，尝试将v2ray-plugin插件复制到mellow安装目录下并使用从ss客户端中复制出来的url也无法使用，请问以后可能会支持吗？
以example.com为例，从ss客户端中复制出来的url如下：
ss://YWVzLTI1Ni1nY206cEFzc1dvcmQ@www.example.com:10086/?plugin=v2ray-plugin_windows_amd64%3btls%3bhost%3dwww.example.com#example_name

### 相关配置
无；

### 相关日志
无；

**Comment by eycorsican** [comment]
我记得 JSON 配置得当就可以支持 https://gist.github.com/eycorsican/4ac150fd0d91c2ae4de0b2959ceb4c52
