### ISSUE TITLE
希望支持app&(ip|domain)的规则

### ISSUE THREAD

**Issue by Luckyvane** [mellow-io/mellow#137]
现有的rule里ip，domain，app是似乎是平级关系，
我试过把app和domain放在同一个rule下，结果两者不是&是|的关系
{
        "type":"field",
        "outboundTag":"SS",
        "app":[
          "chrome"
        ],
        "domain":[
          "geosite:geolocation-!cn"
        ]
}
不知道是不是写法有错误
希望能够支持这种用法

**Comment by a86913179** [comment]
我也有这种需求，之前也试过这种规则，但是不生效，只能指定APP走代理或者直连，不能额外设置IP和domain规则

**Comment by eycorsican** [comment]
验证过没问题
