### ISSUE TITLE
trojan 无法连接

### ISSUE THREAD

**Issue by cqboyone** [mellow-io/mellow#139]
### 使用操作系统类型以及版本
macos 10.3.6

### 使用 Mellow 版本
v0.1.13

### 问题描述
无法使用trojan

### 相关配置
[Endpoint]
Trojan, trojan, trojan://密码@IP:443
Direct, builtin, freedom, domainStrategy=UseIP
Dns-Out, builtin, dns

[RoutingRule]
DOMAIN-KEYWORD, geosite:cn, Direct
GEOIP, cn, Direct
GEOIP, private, Direct
FINAL, Trojan

[Dns]
hijack = Dns-Out

[DnsServer]
localhost
8.8.8.8

### 相关日志
[2020-02-28 22:43:19.116] [info] 2020/02/28 22:43:19 [] [tcp] [remoting_me2me_host] tcp:ip:443

[2020-02-28 22:43:19.117] [info] 2020/02/28 22:43:19 [Warning] [3040944435] v2ray.com/core/app/dispatcher: non existing tag: Trojan

**Comment by HZDeluxe** [comment]
现在还没直接支持trojan吧，搭配trojan客户端可以使用。
下面的address和port改成自己trojan客户端的，yourdomain.com改成服务器的域名就行了。
```
[Endpoint]
Proxy-1, builtin, socks, address=127.0.0.1, port=1080
Direct, builtin, freedom, domainStrategy=UseIP
Dns-Out, builtin, dns

[RoutingRule]
DOMAIN-FULL, yourdomain.com, Direct
DOMAIN-KEYWORD, geosite:cn, Direct
GEOIP, cn, Direct
GEOIP, private, Direct
FINAL, Proxy-1

[Dns]
hijack = Dns-Out

[DnsServer]
localhost
8.8.8.8
```

**Comment by cqboyone** [comment]
> 现在还没直接支持trojan吧，搭配trojan客户端可以使用。
> 下面的address和port改成自己trojan客户端的，yourdomain.com改成服务器的域名就行了。
> 
> ```
> [Endpoint]
> Proxy-1, builtin, socks, address=127.0.0.1, port=1080
> Direct, builtin, freedom, domainStrategy=UseIP
> Dns-Out, builtin, dns
> 
> [RoutingRule]
> DOMAIN-FULL, yourdomain.com, Direct
> DOMAIN-KEYWORD, geosite:cn, Direct
> GEOIP, cn, Direct
> GEOIP, private, Direct
> FINAL, Proxy-1
> 
> [Dns]
> hijack = Dns-Out
> 
> [DnsServer]
> localhost
> 8.8.8.8
> ```
> 
> Duplicate of #125

谢谢你的配置。确实可用了。不过我有两个问题想请教下：
请问下你给的配置能实现只代理被墙的网站吗？
mellow中有个“系统代理”是什么你知道吗？

**Comment by BarryAlanPan** [comment]
> > 现在还没直接支持trojan吧，搭配trojan客户端可以使用。
> > 下面的address和port改成自己trojan客户端的，yourdomain.com改成服务器的域名就行了。
> > ```
> > [Endpoint]
> > Proxy-1, builtin, socks, address=127.0.0.1, port=1080
> > Direct, builtin, freedom, domainStrategy=UseIP
> > Dns-Out, builtin, dns
> > 
> > [RoutingRule]
> > DOMAIN-FULL, yourdomain.com, Direct
> > DOMAIN-KEYWORD, geosite:cn, Direct
> > GEOIP, cn, Direct
> > GEOIP, private, Direct
> > FINAL, Proxy-1
> > 
> > [Dns]
> > hijack = Dns-Out
> > 
> > [DnsServer]
> > localhost
> > 8.8.8.8
> > ```
> > 
> > 
> > Duplicate of #125
> 
> 谢谢你的配置。确实可用了。不过我有两个问题想请教下：
> 请问下你给的配置能实现只代理被墙的网站吗？
> mellow中有个“系统代理”是什么你知道吗？

1. 这个配置能代理的网站数远大于PAC模式，因为他只让cn和内网直连，缺点是可能会有很多流量走代理
2. “系统代理”是真正的全局代理，在你这种配置下千万别用！！千万别用！！千万别用！！因为你现在是trojan客户端的socks正向代理到的mellow来进行分流，你一开全局，trojan客户端的socks代理的端口就无效了，我这样解释你可能不能理解，你可以访问[我的博客](https://www.barrypan.cn/2020/02/06/%E6%AD%A3%E5%90%91%E4%BB%A3%E7%90%86%E7%9A%84%E5%88%86%E6%B5%81%E5%8E%9F%E7%90%86%E4%B8%8E%E4%BB%8B%E7%BB%8D/)了解具体的分流原理

**Comment by cqboyone** [comment]
> > > 现在还没直接支持trojan吧，搭配trojan客户端可以使用。
> > > 下面的address和port改成自己trojan客户端的，yourdomain.com改成服务器的域名就行了。
> > > ```
> > > [Endpoint]
> > > Proxy-1, builtin, socks, address=127.0.0.1, port=1080
> > > Direct, builtin, freedom, domainStrategy=UseIP
> > > Dns-Out, builtin, dns
> > > 
> > > [RoutingRule]
> > > DOMAIN-FULL, yourdomain.com, Direct
> > > DOMAIN-KEYWORD, geosite:cn, Direct
> > > GEOIP, cn, Direct
> > > GEOIP, private, Direct
> > > FINAL, Proxy-1
> > > 
> > > [Dns]
> > > hijack = Dns-Out
> > > 
> > > [DnsServer]
> > > localhost
> > > 8.8.8.8
> > > ```
> > > 
> > > 
> > > Duplicate of #125
> > 
> > 
> > 谢谢你的配置。确实可用了。不过我有两个问题想请教下：
> > 请问下你给的配置能实现只代理被墙的网站吗？
> > mellow中有个“系统代理”是什么你知道吗？
> 
> 1. 这个配置能代理的网站数远大于PAC模式，因为他只让cn和内网直连，缺点是可能会有很多流量走代理
> 2. “系统代理”是真正的全局代理，在你这种配置下千万别用！！千万别用！！千万别用！！因为你现在是trojan客户端的socks正向代理到的mellow来进行分流，你一开全局，trojan客户端的socks代理的端口就无效了，我这样解释你可能不能理解，你可以访问[我的博客](https://www.barrypan.cn/2020/02/06/%E6%AD%A3%E5%90%91%E4%BB%A3%E7%90%86%E7%9A%84%E5%88%86%E6%B5%81%E5%8E%9F%E7%90%86%E4%B8%8E%E4%BB%8B%E7%BB%8D/)了解具体的分流原理

谢谢你的回答。我看了你的博客，写的非常专业。

**Comment by Jeffery-Song** [comment]
开系统代理没啥问题啊，给trojan进程添加一个规则走直连应该就好了？
