### ISSUE TITLE
普通用户在以Admin运行Mellow的配置修改问题

### ISSUE THREAD

**Issue by kobayashikanata** [mellow-io/mellow#140]
### 使用操作系统类型以及版本
Windows10 1909

### 使用 Mellow 版本
v0.1.13

### 问题描述
我是以User0登录的，user0是普通用户，点击运行Mellow使用Admin权限
程序默认创建配置在C:\Users\Administrator目录下（即 C:\Users\Administrator\AppData\Roaming\Mellow\Config）
1.想修改一下配置时，当前的user0无法访问此目录
2.菜单点击ConfigFolder，提示C:\Users\user0\AppData\Roaming\Mellow\Config is unavailable.
这个/mellow/config的路径能自己配置吗？

### 相关配置
默认配置

### 相关日志
暂无

**Comment by zhanxk** [comment]
我也遇到这样的问题的，其实配置文件的位置在Administrator的相应位置下，加载的配置文件可以在preference.json添加文件位置即可。如果你要搭配clashx进行代理的化，clashx也必须要以administrator运行，否则获取不到进程名称的，系统会卡死的，不知道作者能否改进下？
