### ISSUE TITLE
MacOS Dark Mode 下 Mellow 图标区分不明显

### ISSUE THREAD

**Issue by GEM7** [mellow-io/mellow#141]
### 使用操作系统类型以及版本
MacOS Catalina 10.15.3

### 使用 Mellow 版本
v0.1.13

### 问题描述
在 Dark Mode 下 mellow 在开启和关闭状态下菜单栏图标区别不明显。

### 相关配置
和配置无关

### 相关日志
和日志无关

### 原因
在 Light Mode 下，Mellow 任务栏图标的本色是黑色，通过不同的透明度来指示开关状态的不同。在 Light Mode 下显示正常。
在 Dark Mode 下，Mellow 开启状态图标本色是白色，显示正常。但是在关闭状态下图标调用了与 Light Mode 相同的图标。导致了 Dark Mode 下两状态图标难以区分。

希望可以添加一个新的 png 文件供 Dark Mode 下 Mellow 关闭状态时引用，以解决显示区分不明显的问题。

**Comment by eycorsican** [comment]
你把这部分的更改单独开一个 PR 就可以。

**Comment by GEM7** [comment]
> 你把这部分的更改单独开一个 PR 就可以。

请问方便给我一下图标尺寸吗？( 我这边按照菜单栏的尺寸44个像素作为图片的总高度，图标实体部分缩放到 44x44 的 80% 大小来制作的。)

另外，我这边单独为 MacOS 系统制作了 icns 格式的图标。可以一定程度上解决 Retina 屏幕上显示清晰度的问题，这边是做好的[一套图标](https://github.com/GEM7/mellow/tree/update-dl_mmdb/src/assets)。你可以看看菜单栏图标和 icns 图标符不符合你的要求。

**Comment by eycorsican** [comment]
看起来没什么问题就可以了，本来就是随便做的也不知道什么尺寸。
