### ISSUE TITLE
关于 mmdb url 替代地址的一些讨论

### ISSUE THREAD

**Issue by GEM7** [mellow-io/mellow#143]
在 PR #135 中，mmdb URL 的地址被替换为[互联网博物馆](web.archive.org)。 GeoIP 文件需要定期更新，这个地址可能不太能满足需求。建议替换为 Github 上网友自己定期同Maxmind下载并上传的备份文件，以保证时效性。

**Comment by eycorsican** [comment]
注册个 license key 自己下载是最好的，从别的 repo 下载是不能接受的。

**Comment by GEM7** [comment]
> 从别的 repo 下载是不能接受的。

想问个题外话，请问这是被协议所约束吗？

**Comment by eycorsican** [comment]
从别的 repo 下载不就是要看人家脸色更新吗？用 license key 去下载应该没多难，我懒得注册。

**Comment by GEM7** [comment]
也是这么个理。抱歉，我欠考虑了。
