### ISSUE TITLE
为何能够打开YouTube等网站但无法打开Google

### ISSUE THREAD

**Issue by HanYouyang** [mellow-io/mellow#146]
### 使用操作系统类型以及版本
macOS Catalina 10.15.3

### 使用 Mellow 版本
v0.1.12

### 问题描述
能够在trojan打开情况下打开YouTube等各种网站，但是无法使用谷歌搜索

### 相关配置
[Endpoint]
; tag, parser, parser-specific params...
Direct, builtin, freedom, domainStrategy=UseIP
Reject, builtin, blackhole
Dns-Out, builtin, dns
trojan, builtin, socks, address=127.0.0.1, port=1080
; Http-Out, builtin, http, address=192.168.100.1, port=1087, user=myuser, pass=mypass
; Socks-Out, builtin, socks, address=192.168.100.1, port=1080, user=myuser, pass=mypass
; Proxy-1, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:443/path?network=ws&tls=true&ws.host=example.com
; Proxy-2, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:10025?network=tcp
; Proxy-3, ss, ss://aes-128-gcm:pass@192.168.100.1:8888
; Proxy-4, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:443/path?network=http&http.host=example.com%2Cexample1.com&tls=true&tls.allowinsecure=true
; Proxy-7, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:10025?network=kcp&kcp.mtu=1350&kcp.tti=20&kcp.uplinkcapacity=1&kcp.downlinkcapacity=2&kcp.congestion=false&header=none&sockopt.tos=184
; Proxy-8, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:10025?network=quic&quic.security=none&quic.key=&header=none&tls=false&sockopt.tos=184

[EndpointGroup]
; tag, colon-seperated list of selectors or endpoint tags, strategy, strategy-specific params...
; Group-1, Proxy-1:Proxy-2:Proxy-3, latency, interval=300, timeout=6
Group-1, trojan, latency, interval=300, timeout=6

[Routing]
domainStrategy = IPIfNonMatch

[RoutingRule]
; type, filter, endpoint tag or enpoint group tag
DOMAIN-KEYWORD, geosite:category-ads-all, Reject
IP-CIDR, 223.5.5.5/32, Direct
IP-CIDR, 8.8.8.8/32, Group-1
IP-CIDR, 8.8.4.4/32, Group-1
; PROCESS-NAME, cloudmusic.exe, Direct
PROCESS-NAME, trojan, Direct
; PROCESS-NAME, NeteaseMusic, Direct
GEOIP, cn, Direct
GEOIP, private, Direct
PORT, 123, Direct
DOMAIN, www.google.com, Group-1
DOMAIN-FULL, www.google.com, Group-1
DOMAIN-SUFFIX, google.com, Group-1
FINAL, Group-1

[Dns]
; hijack = dns endpoint tag
hijack = Dns-Out
; cliengIp = ip
clientIp = 114.114.114.114

[DnsServer]
; address, port, tag
localhost
223.5.5.5
8.8.8.8, 53, Remote
8.8.4.4

[DnsRule]
; type, filter, dns server tag
DOMAIN-KEYWORD, geosite:geolocation-!cn, Remote
DOMAIN-SUFFIX, google.com, Remote

[DnsHost]
; domain = ip
doubleclick.net = 127.0.0.1

[Log]
loglevel = warning

### 相关日志

我很想知道谷歌后面的那几个 Group-1 作何理解？我为何无法在此时使用谷歌？
似乎在DOMAIN, www.google.com, Direct也无法使用，求教！

**Comment by BarryAlanPan** [comment]
> ### 使用操作系统类型以及版本
> macOS Catalina 10.15.3
> 
> ### 使用 Mellow 版本
> v0.1.12
> 
> ### 问题描述
> 能够在trojan打开情况下打开YouTube等各种网站，但是无法使用谷歌搜索
> 
> ### 相关配置
> [Endpoint]
> ; tag, parser, parser-specific params...
> Direct, builtin, freedom, domainStrategy=UseIP
> Reject, builtin, blackhole
> Dns-Out, builtin, dns
> trojan, builtin, socks, address=127.0.0.1, port=1080
> ; Http-Out, builtin, http, address=192.168.100.1, port=1087, user=myuser, pass=mypass
> ; Socks-Out, builtin, socks, address=192.168.100.1, port=1080, user=myuser, pass=mypass
> ; Proxy-1, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:443/path?network=ws&tls=true&ws.host=example.com
> ; Proxy-2, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:10025?network=tcp
> ; Proxy-3, ss, ss://aes-128-gcm:pass@192.168.100.1:8888
> ; Proxy-4, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:443/path?network=http&http.host=example.com%2Cexample1.com&tls=true&tls.allowinsecure=true
> ; Proxy-7, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:10025?network=kcp&kcp.mtu=1350&kcp.tti=20&kcp.uplinkcapacity=1&kcp.downlinkcapacity=2&kcp.congestion=false&header=none&sockopt.tos=184
> ; Proxy-8, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:10025?network=quic&quic.security=none&quic.key=&header=none&tls=false&sockopt.tos=184
> 
> [EndpointGroup]
> ; tag, colon-seperated list of selectors or endpoint tags, strategy, strategy-specific params...
> ; Group-1, Proxy-1:Proxy-2:Proxy-3, latency, interval=300, timeout=6
> Group-1, trojan, latency, interval=300, timeout=6
> 
> [Routing]
> domainStrategy = IPIfNonMatch
> 
> [RoutingRule]
> ; type, filter, endpoint tag or enpoint group tag
> DOMAIN-KEYWORD, geosite:category-ads-all, Reject
> IP-CIDR, 223.5.5.5/32, Direct
> IP-CIDR, 8.8.8.8/32, Group-1
> IP-CIDR, 8.8.4.4/32, Group-1
> ; PROCESS-NAME, cloudmusic.exe, Direct
> PROCESS-NAME, trojan, Direct
> ; PROCESS-NAME, NeteaseMusic, Direct
> GEOIP, cn, Direct
> GEOIP, private, Direct
> PORT, 123, Direct
> DOMAIN, [www.google.com](http://www.google.com), Group-1
> DOMAIN-FULL, [www.google.com](http://www.google.com), Group-1
> DOMAIN-SUFFIX, google.com, Group-1
> FINAL, Group-1
> 
> [Dns]
> ; hijack = dns endpoint tag
> hijack = Dns-Out
> ; cliengIp = ip
> clientIp = 114.114.114.114
> 
> [DnsServer]
> ; address, port, tag
> localhost
> 223.5.5.5
> 8.8.8.8, 53, Remote
> 8.8.4.4
> 
> [DnsRule]
> ; type, filter, dns server tag
> DOMAIN-KEYWORD, geosite:geolocation-!cn, Remote
> DOMAIN-SUFFIX, google.com, Remote
> 
> [DnsHost]
> ; domain = ip
> doubleclick.net = 127.0.0.1
> 
> [Log]
> loglevel = warning
> 
> ### 相关日志
> 我很想知道谷歌后面的那几个 Group-1 作何理解？我为何无法在此时使用谷歌？
> 似乎在DOMAIN, [www.google.com](http://www.google.com), Direct也无法使用，求教！

1. 你那个Group-1是自己定义的走Trojan的1080端口正向代理
2. 鉴于你youtube访问得了 我怀疑你的DNS可能被污染了 可以尝试清下DNS缓存再访问谷歌

**Comment by wolfleong** [comment]
我也遇到这个问题

**Comment by wolfleong** [comment]
有解决方案吗

**Comment by wolfleong** [comment]
> > ### 使用操作系统类型以及版本
> > macOS Catalina 10.15.3
> > ### 使用 Mellow 版本
> > v0.1.12
> > ### 问题描述
> > 能够在trojan打开情况下打开YouTube等各种网站，但是无法使用谷歌搜索
> > ### 相关配置
> > [Endpoint]
> > ; tag, parser, parser-specific params...
> > Direct, builtin, freedom, domainStrategy=UseIP
> > Reject, builtin, blackhole
> > Dns-Out, builtin, dns
> > trojan, builtin, socks, address=127.0.0.1, port=1080
> > ; Http-Out, builtin, http, address=192.168.100.1, port=1087, user=myuser, pass=mypass
> > ; Socks-Out, builtin, socks, address=192.168.100.1, port=1080, user=myuser, pass=mypass
> > ; Proxy-1, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:443/path?network=ws&tls=true&ws.host=example.com
> > ; Proxy-2, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:10025?network=tcp
> > ; Proxy-3, ss, ss://aes-128-gcm:pass@192.168.100.1:8888
> > ; Proxy-4, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:443/path?network=http&http.host=example.com%2Cexample1.com&tls=true&tls.allowinsecure=true
> > ; Proxy-7, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:10025?network=kcp&kcp.mtu=1350&kcp.tti=20&kcp.uplinkcapacity=1&kcp.downlinkcapacity=2&kcp.congestion=false&header=none&sockopt.tos=184
> > ; Proxy-8, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:10025?network=quic&quic.security=none&quic.key=&header=none&tls=false&sockopt.tos=184
> > [EndpointGroup]
> > ; tag, colon-seperated list of selectors or endpoint tags, strategy, strategy-specific params...
> > ; Group-1, Proxy-1:Proxy-2:Proxy-3, latency, interval=300, timeout=6
> > Group-1, trojan, latency, interval=300, timeout=6
> > [Routing]
> > domainStrategy = IPIfNonMatch
> > [RoutingRule]
> > ; type, filter, endpoint tag or enpoint group tag
> > DOMAIN-KEYWORD, geosite:category-ads-all, Reject
> > IP-CIDR, 223.5.5.5/32, Direct
> > IP-CIDR, 8.8.8.8/32, Group-1
> > IP-CIDR, 8.8.4.4/32, Group-1
> > ; PROCESS-NAME, cloudmusic.exe, Direct
> > PROCESS-NAME, trojan, Direct
> > ; PROCESS-NAME, NeteaseMusic, Direct
> > GEOIP, cn, Direct
> > GEOIP, private, Direct
> > PORT, 123, Direct
> > DOMAIN, [www.google.com](http://www.google.com), Group-1
> > DOMAIN-FULL, [www.google.com](http://www.google.com), Group-1
> > DOMAIN-SUFFIX, google.com, Group-1
> > FINAL, Group-1
> > [Dns]
> > ; hijack = dns endpoint tag
> > hijack = Dns-Out
> > ; cliengIp = ip
> > clientIp = 114.114.114.114
> > [DnsServer]
> > ; address, port, tag
> > localhost
> > 223.5.5.5
> > 8.8.8.8, 53, Remote
> > 8.8.4.4
> > [DnsRule]
> > ; type, filter, dns server tag
> > DOMAIN-KEYWORD, geosite:geolocation-!cn, Remote
> > DOMAIN-SUFFIX, google.com, Remote
> > [DnsHost]
> > ; domain = ip
> > doubleclick.net = 127.0.0.1
> > [Log]
> > loglevel = warning
> > ### 相关日志
> > 我很想知道谷歌后面的那几个 Group-1 作何理解？我为何无法在此时使用谷歌？
> > 似乎在DOMAIN, [www.google.com](http://www.google.com), Direct也无法使用，求教！
> 
> 1. 你那个Group-1是自己定义的走Trojan的1080端口正向代理
> 2. 鉴于你youtube访问得了 我怀疑你的DNS可能被污染了 可以尝试清下DNS缓存再访问谷歌

我也遇到这种情况, 是dns被污染了, 我开域名嗅探就可以了, 但是如果开域名嗅探的话, 有些网络会慢很多, 如微信公众号的一些页面
