### ISSUE TITLE
在MacOS上用root运行提示Operation not permitted

### ISSUE THREAD

**Issue by leizuyi** [mellow-io/mellow#149]
### 使用操作系统类型以及版本

MacOS

### 使用 Mellow 版本

v.0.1.13

### 问题描述

在MacOS上用root运行提示Operation not permitted

### 相关日志

<img width="423" alt="18960e6-8a0a-41ab-89f2-7f84e0f09a4b" src="https://user-images.githubusercontent.com/20525975/76067066-b6504300-5fc9-11ea-87f8-94579d4bc71b.png">

**Comment by nerrrr** [comment]
xattr -rd com.apple.quarantine [EXE DIR]
