### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by lhongtao666** [mellow-io/mellow#154]
### 使用操作系统类型以及版本
Windows10 Pro Insider Preview

### 使用 Mellow 版本
Mellow.Setup.0.1.15.exe

### 问题描述
Frequently pop up the following boxes and disconnect and reconnect automatically after a while
![image](https://user-images.githubusercontent.com/29915310/76235015-73aa9700-6265-11ea-9945-f2fde57c9c56.png)

### 相关配置
_**[Endpoint]
Direct, builtin, freedom, domainStrategy=UseIP
Reject, builtin, blackhole, type=http
Dns-Out, builtin, dns
Proxy-1, vmess1, vmess1://**@**:80?network=tcp&mux=8
Proxy-2, vmess1, vmess1://**@**:80?network=tcp&mux=8
Proxy-3, vmess1, vmess1://**@**:80?network=tcp&mux=8
Proxy-4, vmess1, vmess1://**@**:80?network=tcp&mux=8
Proxy-5, vmess1, vmess1://**@**:80?network=tcp&mux=8
Proxy-6, vmess1, vmess1://**@**:80?network=tcp&mux=8
Proxy-7, vmess1, vmess1://**@**:80?network=tcp&mux=8
Proxy-8, vmess1, vmess1:/**@**:80?network=tcp&mux=8
Proxy-9, vmess1, vmess1://**@**:80?network=tcp&mux=8
Proxy-10, vmess1, vmess1://**@**:80?network=tcp&mux=8

[EndpointGroup]
MyGroup, Proxy-1:Proxy-2:Proxy-3:Proxy-4:Proxy-5:Proxy-6:Proxy-7:Proxy-8:Proxy-9:Proxy-10, latency, interval=300, timeout=6

[Routing]
domainStrategy = IPIfNonMatch

[RoutingRule]
;Ads Reject
DOMAIN-KEYWORD, geosite:category-ads-all, Reject
IP-CIDR, 8.8.8.8/32, MyGroup
GEOIP, cn, Direct
GEOIP, private, Direct
DOMAIN, test.com, Proxy-3
DOMAIN-KEYWORD, geosite:cn, Direct
DOMAIN-KEYWORD, bilibili, Direct
FINAL, MyGroup

[Dns]
hijack = Dns-Out
clientIp = 114.114.114.114

[DnsServer]
; address, port, tag
localhost
114.114.114.114
8.8.8.8, 53, Remote
8.8.4.4

[DnsRule]
DOMAIN-KEYWORD, geosite:geolocation-!cn, Remote
DOMAIN, www.google.com, Remote
DOMAIN-FULL, www.twitter.com, Remote
DOMAIN-SUFFIX, google.com, Remote

[DnsHost]
; domain = ip
localhost = 127.0.0.1

[Log]
loglevel = warning**_

### 相关日志
Set TAP adapter metric to 2.
Ok.

TAP network device added successfully.

[2020-03-09 18:15:35.916] [info] Set system proxy with command: "C:\Users\sdss\AppData\Local\Programs\Mellow\resources\src\helper\configure_proxy.bat" "on" 2887
[2020-03-09 18:15:36.039] [info] Core started.
[2020-03-09 18:15:39.307] [info] The default gateway before configuring routes:
[2020-03-09 18:15:39.308] [info] { gateway: '192.168.21.1', interface: 'WLAN' }
[2020-03-09 18:15:39.339] [info] The TUN interface before configuring routes:
[2020-03-09 18:15:39.340] [info] { address: '10.255.0.2', interface: 'mellow-tap0' }
[2020-03-09 19:29:57.314] [info] Screen locked.
[2020-03-10 00:19:55.352] [info] Screen unlocked.
[2020-03-10 00:20:11.037] [info] Original gateway is 192.168.21.1
[2020-03-10 00:20:11.065] [info] Original send through 192.168.21.106 WLAN
[2020-03-10 00:20:11.066] [info] 2020/03/09 18:15:36 Start session stater.
2020/03/09 18:15:36 TAP device component ID: {BF619D76-66FD-4A60-9393-F8BE1FE55E6D}
2020/03/09 18:15:36 TAP device name: mellow-tap0
2020/03/09 18:15:36 Set mellow-tap0 with net/mask: 10.255.0.2/255.255.255.0 through DHCP
2020/03/09 18:15:36 Set mellow-tap0 with DNS: 223.5.5.5,1.1.1.1 through DHCP
2020/03/09 18:15:36 Relay ICMP packets.
2020/03/09 18:15:36 Running tun2socks
2020/03/09 18:15:37 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:15:37 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:15:37 [] [udp] [chrome.exe] udp:224.0.0.251:5353
2020/03/09 18:15:37 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:15:39 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:15:39 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:15:40 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:15:40 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:15:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:15:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:16:12 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:16:12 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:16:12 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:16:12 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:16:12 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:16:12 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:16:18 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:16:18 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:16:18 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:16:18 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:16:18 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:16:18 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:16:42 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:16:42 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:17:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:17:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:19:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:19:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:21:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:21:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:22:38 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:22:38 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:22:38 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:22:38 [] [udp] [msedge.exe] udp:224.0.0.251:5353
2020/03/09 18:23:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:23:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:24:50 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:24:50 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:24:50 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:24:50 [] [udp] [chrome.exe] udp:224.0.0.251:5353
2020/03/09 18:25:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:25:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:26:28 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:27:00 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:27:00 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:27:00 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:27:00 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:27:00 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:27:00 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:27:00 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:27:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:27:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:27:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:27:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:27:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:27:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:27:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:27:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:29:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:29:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:31:11 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:31:11 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:31:11 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:31:11 [] [udp] [msedge.exe] udp:224.0.0.251:5353
2020/03/09 18:31:18 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:31:18 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:31:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:31:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:31:54 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:31:54 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:33:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:33:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:34:38 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:34:38 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:34:38 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:34:38 [] [udp] [chrome.exe] udp:224.0.0.251:5353
2020/03/09 18:35:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:35:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:37:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:37:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:37:54 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:37:54 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:37:54 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:37:54 [] [udp] [msedge.exe] udp:224.0.0.251:5353
2020/03/09 18:39:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:39:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:41:29 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:41:29 [] [udp] [chrome.exe] udp:224.0.0.251:5353
2020/03/09 18:41:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:41:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:42:01 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:42:01 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:42:01 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:42:01 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:42:01 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:42:01 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:42:01 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:42:07 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:42:07 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:42:07 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:42:07 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:42:07 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:42:07 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:43:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:43:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:43:50 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:43:50 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:43:50 [] [udp] [msedge.exe] udp:224.0.0.251:5353
2020/03/09 18:45:30 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:45:30 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:45:30 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:45:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:45:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:47:31 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:47:31 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:47:31 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:47:31 [] [udp] [chrome.exe] udp:224.0.0.251:5353
2020/03/09 18:47:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:47:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:49:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:49:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:49:50 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:49:50 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:49:50 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:49:50 [] [udp] [msedge.exe] udp:224.0.0.251:5353
2020/03/09 18:51:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:51:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:53:06 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:53:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:53:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:53:06 [] [udp] [chrome.exe] udp:224.0.0.251:5353
2020/03/09 18:53:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:53:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:54:46 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:54:46 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:55:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:55:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:56:26 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:56:26 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:56:26 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:56:26 [] [udp] [msedge.exe] udp:224.0.0.251:5353
2020/03/09 18:56:28 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:57:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:57:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:59:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 18:59:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 18:59:42 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 18:59:42 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:59:42 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 18:59:42 [] [udp] [msedge.exe] udp:224.0.0.251:5353
2020/03/09 19:01:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:01:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:01:54 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 19:01:54 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:01:54 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:01:54 [] [udp] [chrome.exe] udp:224.0.0.251:5353
2020/03/09 19:03:34 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:03:34 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:03:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:03:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:05:14 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 19:05:14 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:05:14 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:05:14 [] [udp] [chrome.exe] udp:224.0.0.251:5353
2020/03/09 19:05:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:05:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:06:26 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:06:26 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:07:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:07:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:08:10 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:08:10 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:09:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:09:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:09:54 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 19:09:54 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:09:54 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:11:26 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:11:26 [] [udp] [msedge.exe] udp:224.0.0.251:5353
2020/03/09 19:11:28 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:11:38 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:11:38 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:11:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:11:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:12:00 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:12:00 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:12:00 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:12:00 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:12:00 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:12:00 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:12:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:12:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:12:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:12:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:12:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:12:06 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:13:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:13:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:14:54 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 19:14:54 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:14:54 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:14:54 [] [udp] [chrome.exe] udp:224.0.0.251:5353
2020/03/09 19:15:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:15:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:17:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:17:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:19:14 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 19:19:14 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:19:14 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:19:14 [] [udp] [chrome.exe] udp:224.0.0.251:5353
2020/03/09 19:19:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:19:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:21:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:21:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:22:30 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 19:22:30 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:22:30 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:22:30 [] [udp] [msedge.exe] udp:224.0.0.251:5353
2020/03/09 19:23:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:23:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:25:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:25:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:26:29 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:26:29 [] [udp] [msedge.exe] udp:224.0.0.251:5353
2020/03/09 19:27:01 [] [udp] [unknown process] udp:10.255.0.255:137
2020/03/09 19:27:01 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:27:01 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:27:01 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:27:07 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:27:07 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:27:07 [] [udp] [unknown process] udp:224.0.0.252:5355
2020/03/09 19:27:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:27:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:29:42 [] [udp] [chrome.exe] udp:239.255.255.250:1900
2020/03/09 19:29:42 [] [udp] [msedge.exe] udp:239.255.255.250:1900
2020/03/09 19:29:59 copying data failed: The I/O operation has been aborted because of either a thread exit or an application request.

[2020-03-10 00:20:11.068] [info] 2020/03/09 18:15:36 [Warning] v2ray.com/core: V2Ray started
2020/03/09 18:16:42 [] tcp:127.0.0.1:64100 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 18:18:22 [] tcp:127.0.0.1:64226 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 18:21:02 [] tcp:127.0.0.1:64419 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 18:31:54 [] tcp:127.0.0.1:63887 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 18:34:38 [] tcp:127.0.0.1:52186 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 18:39:34 [] tcp:127.0.0.1:52463 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 18:41:10 [] tcp:127.0.0.1:52557 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 18:46:38 [] tcp:127.0.0.1:55237 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 18:52:02 [] tcp:127.0.0.1:55539 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 18:53:42 [] tcp:127.0.0.1:55631 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 18:55:22 [] tcp:127.0.0.1:55714 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 18:58:06 [] tcp:127.0.0.1:62556 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:00:18 [] tcp:127.0.0.1:62677 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:01:54 [] tcp:127.0.0.1:62761 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:03:02 [] tcp:127.0.0.1:62820 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:06:26 [] tcp:127.0.0.1:63011 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:08:10 [] tcp:127.0.0.1:63099 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:09:54 [] tcp:127.0.0.1:63191 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:11:38 [] tcp:127.0.0.1:63319 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:12:46 [] tcp:127.0.0.1:58804 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:17:06 [] tcp:127.0.0.1:59063 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:18:10 [] tcp:127.0.0.1:59122 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:19:50 [] tcp:127.0.0.1:59217 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:22:30 [] tcp:127.0.0.1:59365 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:25:54 [] tcp:127.0.0.1:59537 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:27:50 [] tcp:127.0.0.1:59653 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72
2020/03/09 19:28:54 [] tcp:127.0.0.1:58474 rejected [ ]  v2ray.com/core/proxy/socks: unknown Socks version: 72

[2020-03-10 00:20:11.070] [info] Device suspended.
[2020-03-10 00:20:11.071] [info] Shutting down the core.
[2020-03-10 00:20:12.086] [info] Device resumed.
[2020-03-10 00:20:12.087] [info] Device suspended.
[2020-03-10 00:20:12.088] [info] Shutting down the core.
[2020-03-10 00:20:13.057] [info] Device resumed.
[2020-03-10 00:20:13.059] [info] Device suspended.
[2020-03-10 00:20:13.060] [info] Shutting down the core.
[2020-03-10 00:20:14.109] [info] Device resumed.
[2020-03-10 00:20:14.133] [info] Core stopped, code 1 signal null
[2020-03-10 00:20:14.134] [info] Core will restart upon device resume.
[2020-03-10 00:20:15.231] [info] Original gateway is 192.168.21.1
[2020-03-10 00:20:15.264] [info] Original send through 192.168.21.106 WLAN
[2020-03-10 00:20:15.269] [info] Ensuring tap device sets up correctly.
[2020-03-10 00:20:15.277] [info] management RPC error:
[2020-03-10 00:20:15.278] [info] Error: connect ECONNREFUSED 127.0.0.1:2884
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
[2020-03-10 00:20:15.279] [info] management RPC error:
[2020-03-10 00:20:15.279] [info] Error: connect ECONNREFUSED 127.0.0.1:2884
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
[2020-03-10 00:20:16.349] [info] Original gateway is 192.168.21.1
[2020-03-10 00:20:16.379] [info] Original send through 192.168.21.106 WLAN
[2020-03-10 00:20:16.384] [info] Ensuring tap device sets up correctly.
[2020-03-10 00:20:16.391] [info] management RPC error:
[2020-03-10 00:20:16.392] [info] Error: connect ECONNREFUSED 127.0.0.1:2884
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
[2020-03-10 00:20:17.512] [info] Original gateway is 192.168.21.1
[2020-03-10 00:20:17.542] [info] Original send through 192.168.21.106 WLAN
[2020-03-10 00:20:17.545] [info] Ensuring tap device sets up correctly.
[2020-03-10 00:20:17.553] [info] management RPC error:
[2020-03-10 00:20:17.553] [info] Error: connect ECONNREFUSED 127.0.0.1:2884
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
[2020-03-10 00:20:22.040] [info] Set 10.255.0.1 as the default gateway.
[2020-03-10 00:20:27.414] [info] TAP network device already exists.
(Re-)enabling TAP network device...

This network connection does not exist.

**Comment by lhongtao666** [comment]
![image](https://user-images.githubusercontent.com/29915310/76248369-2980e000-627c-11ea-9fb6-658c240f1377.png)

**Comment by lhongtao666** [comment]
![image](https://user-images.githubusercontent.com/29915310/76274369-79cb6280-62bb-11ea-93bf-856d51a4cfe6.png)

**Comment by lhongtao666** [comment]
After some sort like above, it would be opened successfully automatically.
![image](https://user-images.githubusercontent.com/29915310/76274464-c020c180-62bb-11ea-8c7b-c461b7083c38.png)

**Comment by lhongtao666** [comment]
But just a while, it would failed again.
![image](https://user-images.githubusercontent.com/29915310/76274541-eba3ac00-62bb-11ea-8443-768364ea6da2.png)

**Comment by lhongtao666** [comment]
Especially when I wake up the laptop.

**Comment by a86913179** [comment]
Related: https://github.com/mellow-io/mellow/issues/222
