### ISSUE TITLE
怎么配置mac电脑网关翻墙啊，让电视盒子也能翻墙

### ISSUE THREAD

**Issue by cyxcw1** [mellow-io/mellow#165]
### 使用操作系统类型以及版本
macOS 10.15.3

### 使用 Mellow 版本
0.1.16

### 问题描述
配合v2rayX，已经能电脑全局翻墙了，但是怎么配置mac电脑网关翻墙啊，让电视盒子也能翻墙？

### 相关配置
这是我现在的配置：
{
  "log": {
    "loglevel": "debug"
  },
  "outbounds": [
    {
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 1081
          }
        ]
      },
      "tag": "v2ray"
    },
    {
      "protocol": "freedom",
      "tag": "direct"
    }
  ],
  "routing": {
    "rules": [
      {
        "app": [
          "V2RayX",
          "v2ray"
        ],
        "type": "field",
        "outboundTag": "direct"
      }
    ]
  }
}

**Comment by fbion** [comment]
https://github.com/monsterxx03/snet/issues/8
https://github.com/monsterxx03/snet/issues/6

**Comment by eycorsican** [comment]
README 中有说明
