### ISSUE TITLE
访问网站经常出现“安全检查!|百度云加速”

### ISSUE THREAD

**Issue by sagexy** [mellow-io/mellow#166]
### 使用操作系统类型以及版本
macOS 10.15.3

### 使用 Mellow 版本
v0.1.16

### 问题描述
很多网站经常出现“安全检查!|百度云加速” 需要输入验证码才可以访问

![image](https://user-images.githubusercontent.com/4734448/76915679-16fc4b80-68f9-11ea-8b5e-2632ca85f937.png)

不知道是我这边的问题，还是大部分网站的问题，使用或不使用系统代理选项都会出现该问题

### 问题复现步骤
浏览器访问大部分网站都会出现需要输入验证码问题，输入之后当天之内不会出现，第二天访问或者隔段时间访问又会出现输入验证码问题

### 相关配置

[Endpoint]
; tag, parser, parser-specific params...
Direct, builtin, freedom, domainStrategy=UseIP
Reject, builtin, blackhole
Dns-Out, builtin, dns
;Http-Out, builtin, http, address=127.0.0.1, port=1087
;Socks-Out, builtin, socks, address=127.0.0.1, port=1080
gcp, vmess1, vmess1://uuid@xxx.com:443/xxxxx/?network=ws&tls=true&ws.host=xxx.com
bwg, vmess1, vmess1://uuid@xxx.com:443/xxxxx/?network=ws&tls=true&ws.host=xxx.com

[EndpointGroup]
; tag, colon-seperated list of selectors or endpoint tags, strategy, strategy-specific params...
Proxy, gcp:bwg, latency, interval=300, timeout=6

[Routing]
domainStrategy = IPIfNonMatch

[RoutingRule]
; type, filter, endpoint tag or enpoint group tag
DOMAIN-KEYWORD, geosite:category-ads-all, Reject

; Direct
GEOIP, cn, Direct
GEOIP, private, Direct
PORT, 123, Direct
DOMAIN-KEYWORD, geosite:cn, Direct

; Proxy
DOMAIN,static.realm.io,Proxy
DOMAIN,codeload.github.com,Proxy
DOMAIN-KEYWORD,github,Proxy
DOMAIN-KEYWORD,amazon,Proxy
DOMAIN-KEYWORD,reddit,Proxy
DOMAIN-KEYWORD,btbtt,Proxy
......
......
DOMAIN-SUFFIX,telegra.ph,Proxy
DOMAIN-SUFFIX,telegram.org,Proxy
IP-CIDR,91.108.56.0/22,Proxy
IP-CIDR,91.108.4.0/22,Proxy
IP-CIDR,91.108.8.0/22,Proxy
IP-CIDR,109.239.140.0/24,Proxy
IP-CIDR,149.154.160.0/20,Proxy
IP-CIDR,149.154.164.0/22,Proxy

FINAL, Direct

[Dns]
; hijack = dns endpoint tag
hijack = Dns-Out
; cliengIp = ip
clientIp = 1.1.1.1

[DnsServer]
; address, port, tag
localhost
223.5.5.5
8.8.8.8, 53, Remote
8.8.4.4

[DnsRule]
; type, filter, dns server tag
DOMAIN-KEYWORD, geosite:geolocation-!cn, Remote
DOMAIN-SUFFIX, google.com, Remote

[DnsHost]
; domain = ip
doubleclick.net = 127.0.0.1

[Log]
loglevel = warning

### 相关日志、截图

截图在问题描述里面

**Comment by eycorsican** [comment]
本该直连的请求都走代理了吧？看看请求记录

**Comment by sagexy** [comment]
> 本该直连的请求都走代理了吧？看看请求记录

没有 我用的GFW模式 其他都是FINAL, Direct
