### ISSUE TITLE
Windows下系统代理无法正常工作

### ISSUE THREAD

**Issue by zhuzeitou** [mellow-io/mellow#170]
### 使用操作系统类型以及版本
Win10 1909

### 使用 Mellow 版本
v0.1.17

### 问题描述
开启系统代理后，浏览器无法正常工作

### 问题复现步骤
1.启动Mellow，不开启系统代理，一切正常
2.开启系统代理，浏览器无法正常工作
3.取消系统代理，恢复正常

### 相关配置
与配置无关，查看端口情况发现可能是socks5端口未监听

### 相关日志、截图
浏览器代理pac为`http://127.0.0.1:2887/proxy.pac`
其内容为`function FindProxyForURL(url, host) { return "SOCKS5 127.0.0.1:2886; SOCKS 127.0.0.1:2886" }`
执行`netstat -ano`发现并没有监听2886端口，但是有一个2884端口，对应pid 21360为`core.exe`，~~不确定2884是否为socks5端口~~查看代码后发现是`coreRpcPort`
截图如下：
![image](https://user-images.githubusercontent.com/4777466/77234618-d51a2080-6bea-11ea-957d-8983d59ced0a.png)
![image](https://user-images.githubusercontent.com/4777466/77234653-1ad6e900-6beb-11ea-9166-80de06c5c622.png)

**Comment by JimHan75d8c5** [comment]
似乎只有在Conf配置文件下，Mellow会自动设置 socks/http Inbound

**Comment by zhuzeitou** [comment]
没仔细看，印象中0.1.15是可以的但0.1.16开始就不行了，晚点再去看下
