### ISSUE TITLE
macOS 菜单栏图标不显示

### ISSUE THREAD

**Issue by chrisniael** [mellow-io/mellow#171]
### 使用操作系统类型以及版本

MacBook Pro
macOS 10.15.3

### 使用 Mellow 版本

mellow 0.1.17

### 问题描述

不外接显示器时，菜单栏不显示 Mellow 的图标，但是会占用位置，点击能正常弹出子菜单。但是外接显示器使用时，菜单栏能正确显示 Mellow 的图标。

### 相关日志、截图

<img width="118" alt="image" src="https://user-images.githubusercontent.com/5593254/77248530-03dcd900-6c75-11ea-9572-430c4044f0c5.png">

**Comment by eycorsican** [comment]
哪个型号 mbp 呢，跟屏幕分辨率有关？

**Comment by chrisniael** [comment]
@eycorsican MacBook Pro 15.6 2016年的机器，外接的显示器是 LG Ultrafine 5k，不确定是什么问题，之前的几个版本也出现过，回头我换旧版本试试，再回复。

**Comment by chrisniael** [comment]
@eycorsican 外接显示器时也出现 Tray 图标不显示的情况了，不过我通过手动关闭/开启暗黑模式，Tray 图标又显示出来了，尝试复现不显示的情况，就是复现不了。
系统偏好设置 - 通用 - 外观 - 浅色/深色/自动

**Comment by chrisniael** [comment]
删除了 `~/Library/Application Support/Mellow` 目录中的内容，删除前备份一下之前的配置。

```bash
cp ~/Library/Application\ Support/Mellow/config/* ~/Desktop/
rm -rf ~/Library/Application\ Support/Mellow
```

然后重新配置了一下 Mellow，这样操作之后目前还没复现过。


暂时把 issue 关掉了，如果再出现这种情况，再提。

**Comment by ihewro** [comment]
Mac下的深色模式适配似乎有点问题：
- 外观模式选择自动，晚上会自动切换到mellow白色图标
- 早上打开电脑后，图标还是白色，看不到图标
