### ISSUE TITLE
win10 启动后无法创建虚拟网卡，没有托盘图标

### ISSUE THREAD

**Issue by albertofwb** [mellow-io/mellow#173]
### 使用操作系统类型以及版本
win10 1909 18363.720

### 使用 Mellow 版本
0.1.17

### 问题描述
没有创建虚拟网卡设备，没有添加路由表，没有托盘图标，也没有报错

### 问题复现步骤
安装完毕，启动软件，鼠标转三五个圈圈，然后旧什么都没了。
在 任务管理器中可以看到 两个 mellow 进程

### 相关配置
由于没有托盘图标，所以无法设置任何配置
电脑本身安装有 vmware workstation 15 不过我 disable 了 vmnet1 和 vmnet8

### 相关日志、截图
日志看起来似乎没啥问题？

[2020-03-23 09:28:44.693] [info] Created config folder C:\Users\Albert.000\AppData\Roaming\Mellow\config
[2020-03-23 09:28:44.848] [info] Mellow (0.1.17) started.
[2020-03-23 09:29:26.534] [info] Mellow (0.1.17) started.
[2020-03-23 09:32:15.787] [info] Mellow (0.1.17) started.
[2020-03-23 09:32:54.874] [info] Mellow (0.1.17) started.
[2020-03-23 09:34:03.731] [info] Mellow (0.1.17) started.

![image](https://user-images.githubusercontent.com/5900716/77273062-a2a51c00-6ced-11ea-93e7-93b6697ad95d.png)
![image](https://user-images.githubusercontent.com/5900716/77273083-ae90de00-6ced-11ea-8407-c49693836f53.png)

![image](https://user-images.githubusercontent.com/5900716/77273102-b94b7300-6ced-11ea-9d39-c64c3a2402f3.png)

**Comment by albertofwb** [comment]
同版本在我的 Macbook 上一切正常。

windows 上在使用 mellow 之前，我使用  vmware 安装了一个 openwrt lede，给其设置了两个网卡， bridge 和 NAT。宿主机所有流量走 NAT 网络，openwrt 通过 iptables 分流后从 bridge 出，这套方案挺稳定的

感觉现在的这个问题，核心原因是创建虚拟网卡失败，但软件没有给出提示，日志里也没有线索

**Comment by eycorsican** [comment]
没连接前不会创建TAP，但没托盘图标就没法点连接，至于为什么没图标我也不清楚

**Comment by justin201802** [comment]
遇到了同样的问题， 安装完之后， 没有托盘图标。
启动日志里面没有报错。

**Comment by testermania** [comment]
icon is is hidden in black background on the task manager. v0.1.13 only showing, mellow going to bad for win users.

**Comment by Moeologist** [comment]
没图标可能是因为WIN10暗色主题的Taskbar默认颜色和mellow ICON颜色一样，无法创建Adaptor，手动创建名为mellow-tap0的Adaptor后可以工作，
https://github.com/mellow-io/mellow/blob/a01492073de7656405b9ba7ef7ca1b2adfc455f7/src/main.js#L68 
目测是ensure_tap_device.bat的实现过于草率，不仅自动安装了驱动，还通过比对（netsh输出到文件然后比对字符串）驱动安装前后设备的变化，然后netsh将新创建的设备改名。如果先前安装了旧版本驱动（或已安装但是失败）则这个脚本无法工作，而且这个脚本在
https://github.com/mellow-io/mellow/blob/c6a20f9c7444af2cdadadd8c4fe7e7b7350336f9/src/helper/win32/ensure_tap_device.bat#L105
失败的话不会退出，如果用户不停重试直接CPU全核心100%。
建议建议windows用户手动安装TAP驱动包，再调用驱动包提供的tapinstall安装Adaptor，而不是直接tap-windows-9.24.2-I601-Win10.exe /S ，可是如何自动将Adaptor改名除了ensure_tap_device.bat的做法似乎没有更优解决方案。

**Comment by Moeologist** [comment]
可能的有关问题 #207 #232 #267

**Comment by Cherrymelon** [comment]
win10实际是托盘图标的，但是深色模式容易走眼

**Comment by sagasm** [comment]
我介绍个手动安装方法:
1. 如果没有安装名称为mellow-tap0的虚拟网卡,运行mellow提供的tap-windows-9.24.2-I601-Win10.exe或者tap-windows-9.24.2-I601-Win7.exe,然后把生成的虚拟网卡改名为mellow-tap0.
2.用winrar解压mellow安装程序到合适目录,运行该目录的mellow.exe即可.
