### ISSUE TITLE
PROCESS-NAME无法自动匹配大小写,有大小写区别时不会正常代理

### ISSUE THREAD

**Issue by nic8888dsf** [mellow-io/mellow#175]
### 使用操作系统类型以及版本
windows10专业版

### 使用 Mellow 版本
0.1.17

### 问题描述
PROCESS-NAME下,当有大小写的区别时不会正常代理,能不能调整下,不管大小写都能匹配上,本身对系统来说大小写不匹配他们也都是同名的.

**Comment by eycorsican** [comment]
用通配符表示

**Comment by nic8888dsf** [comment]
通配符我只看到有个*匹配所有,比如RuneScape.exe这个进程我需要他不论大小写都能匹配上,我应该怎么写通配符呢?能帮忙给个例子吗?,这个其实在进程名比对的时候先把字符串全部格式化大写或者小写在比对就可以了吧,主要是这种大小写的问题太容易忽视了,完全没发现没挂上代理,直到封号了才发现问题...

**Comment by eycorsican** [comment]
看 `连接记录` 是个基本操作

**Comment by nic8888dsf** [comment]
大神的这个软件看起真的很方便,基于虚拟网卡的应该很稳定,之前用过proxifier,每次玩过英雄联盟后代理就会失效,然后就要重装很麻烦,但是第一次用这个东西不是很明白,这个进程代理是啥原理呀?网上搜了搜说tun是靠修改路由表来代理的,这个进程会出现进程识别出错然后导致从本地IP上网的情况吗?因为想用来玩游戏,但是如果没挂上代理很容易导致IP异常然后就锁号了,我只想挂特定游戏相关的进程,其他都不需要代理,主要看连接记录会有很多未知连接什么的,不知道进程代理稳定吗?
