### ISSUE TITLE
mellow可以设置条件代理吗？

### ISSUE THREAD

**Issue by ynotoony** [mellow-io/mellow#179]
### 使用操作系统类型以及版本
mac

### 问题描述
就是连接家里的wifi的时候，不用代理；连接公司的wifi的时候再启动代理。

**Comment by ynotoony** [comment]
看了一下配置文件，routingrules里面有一个network的设置，但是配置项是udp:tcp，跟wifi的ssid不一样，不知道应该怎么设置

**Comment by eycorsican** [comment]
不可以
