### ISSUE TITLE
macOS 转发 Trojan 流量有几点疑问。

### ISSUE THREAD

**Issue by jmyz0455** [mellow-io/mellow#180]
### 使用操作系统版本以及 Mellow 版本

macOS 10.15 & Mellow v0.1.17

### 目前情况

本机已在 8888 端口运行 Trojan ，已通过配置 Mellow 实现系统全局代理，但是对配置有疑问的地方。

### 配置经历（可跳过）

首先我是尝试 [说明](https://github.com/mellow-io/mellow/blob/master/README.md) 里的全局配置，连接后，Trojan 有接收到流量，但日志显示（大量重复的输出我就不全部贴上来了，基本都是这两句）：

> [2020-03-26 10:09:45] [INFO] 127.0.0.1:63475 requested connection to ***.google.com:443
> [2020-03-26 10:09:46] [INFO] 127.0.0.1:63475 disconnected, 0 bytes received, 589 bytes sent, lasted for 1 seconds

可能是请求的流量没有得到回应，配置 1 如下：

`[Endpoint]
MyProxyServer, builtin, socks, address=127.0.0.1, port=8888
Dns-Out, builtin, dns

[RoutingRule]
FINAL, MyProxyServer

[Dns]
hijack = Dns-Out

[DnsServer]
8.8.8.8
8.8.4.4`

然后参考 [issues125](https://github.com/mellow-io/mellow/issues/125) 里 lazytiger 的配置来修改，就可以正常看外网了，配置 2 如下：

`[Endpoint]
MyProxyServer, builtin, socks, address=127.0.0.1, port=8888
Direct, builtin, freedom, domainStrategy=UseIP
Dns-Out, builtin, dns

[RoutingRule]
DOMAIN-KEYWORD, geosite:cn, Direct
DOMAIN-FULL, MyDomain.com, Direct
GEOIP, cn, Direct
GEOIP, private, Direct
FINAL, MyProxyServer

[Dns]
hijack = Dns-Out

[DnsServer]
localhost
8.8.8.8

### 问题描述

1. 我是小白，看见 issue 里很多人对 Mellow 配置非常熟悉，请问除了 README ，你们是从哪里了解到这么详细的配置项解释？难道都是直接看源码理解的嚒，想搞懂 [更多配置](https://github.com/mellow-io/mellow#%E6%9B%B4%E5%A4%9A%E9%85%8D%E7%BD%AE) 里的选项。

2. 请问配置 1  为什么不行？难道说 DnsServer 里的 localhost 是必须的？不知道是哪一项起作用了。

3. 其他人的配置里会设置 PROCESS-NAME 来免除代理某些程序，在 Windows 里可以写上 trojan.exe ，那在 macOS 是不是写上 trojan 就可以？因为没法验证所以我也不知道是不是有效。

**Comment by rampageX** [comment]
```
DOMAIN-FULL, MyDomain.com, Direct
GEOIP, private, Direct
```

不加这两句，很容易回环。

**Comment by eycorsican** [comment]
我只回答你第 2 个。

![zh](https://user-images.githubusercontent.com/33020880/77622130-adbfac80-6f78-11ea-8977-f65da116340b.png)

流程图大概就这样，如果不用规则排除 trojan 流量，流量就会这样走：

1. 应用进程（例如 chrome.exe 发请求 http://1.2.3.4/index.html ，简单起见用 IP 不涉及 DNS）
2. 路由表
3. TUN
4. Mellow -> SOCKS -> 127.0.0.1（红框部分）
5. 路由表
6. 环回接口
7.  应用进程（trojan.exe 向代理服务器发请求）
8. 路由表
9. TUN
10. Mellow （因为没 trojan 相应规则，根据 `FINAL, MyProxyServer`）-> SOCKS -> 127.0.0.1
11. 这里开始接上面 5 不断循环

如果加了代理服务器的域名或 trojan.exe 进程规则指向 Direct，则：

10. Mellow （根据 `PROCESS-NAME, trojan.exe, Direct`）-> Direct
11. 路由表
12. 以太网
13. 代理服务器
14. 目标网站（即1.2.3.4）

这里很重要一点是任何指向 Direct 的流量经路由表后都不会再次进入 TUN。

**Comment by paomuer** [comment]
> 如果加了代理服务器的域名或 trojan.exe 进程规则指向 Direct，则：
> 
> 1. Mellow （根据 `PROCESS-NAME, trojan.exe, Direct`）-> Direct
> 2. 路由表
> 3. 以太网
> 4. 代理服务器
> 5. 目标网站（即1.2.3.4）
> 
> 这里很重要一点是任何指向 Direct 的流量经路由表后都不会再次进入 TUN。

这部分似乎有点明白了 但是看trojan的日志一直是 
SSL handshake failed with ip:port Operation canceled
或者 stream truncated 
不进TUN不是应该直接走到代理域名 -> 目标网站 吗

**Comment by paomuer** [comment]
并且mellow的日志会报错 ：不能建立连接 
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > read tcp 127.0.0.1:64078->127.0.0.1:1080: read: connection reset by peer

**Comment by jmyz0455** [comment]
> 我只回答你第 2 个。
> 
> ![zh](https://user-images.githubusercontent.com/33020880/77622130-adbfac80-6f78-11ea-8977-f65da116340b.png)
> 
> 流程图大概就这样，如果不用规则排除 trojan 流量，流量就会这样走：
> 
> 1. 应用进程（例如 chrome.exe 发请求 http://1.2.3.4/index.html ，简单起见用 IP 不涉及 DNS）
> 2. 路由表
> 3. TUN
> 4. Mellow -> SOCKS -> 127.0.0.1（红框部分）
> 5. 路由表
> 6. 环回接口
> 7. 应用进程（trojan.exe 向代理服务器发请求）
> 8. 路由表
> 9. TUN
> 10. Mellow （因为没 trojan 相应规则，根据 `FINAL, MyProxyServer`）-> SOCKS -> 127.0.0.1
> 11. 这里开始接上面 5 不断循环
> 
> 如果加了代理服务器的域名或 trojan.exe 进程规则指向 Direct，则：
> 
> 1. Mellow （根据 `PROCESS-NAME, trojan.exe, Direct`）-> Direct
> 2. 路由表
> 3. 以太网
> 4. 代理服务器
> 5. 目标网站（即1.2.3.4）
> 
> 这里很重要一点是任何指向 Direct 的流量经路由表后都不会再次进入 TUN。

非常感谢你的回答，这张图很清晰，所以 [更多配置](https://github.com/mellow-io/mellow#%E6%9B%B4%E5%A4%9A%E9%85%8D%E7%BD%AE) 里面 RoutingRule 这么多项按我的理解无非就是决定流量是走拒绝、直连和代理流程。

突然想到一个问题，PROCESS-NAME 可以配置两个，那 DOMAIN 配置多个是都生效还是覆盖？

仔细看了下，原来 ; 是注释符号啊，长见识了。

**Comment by paomuer** [comment]
同为小白 
参考jmyz0455的配置
[Endpoint]
MyProxyServer, builtin, socks, address=127.0.0.1, port=我的端口号
Direct, builtin, freedom, domainStrategy=UseIP
Dns-Out, builtin, dns

[RoutingRule]
DOMAIN-KEYWORD, geosite:cn, Direct
DOMAIN-FULL, 我的代理域名, Direct
GEOIP, cn, Direct
GEOIP, private, Direct
FINAL, MyProxyServer

[Dns]
hijack = Dns-Out

[DnsServer]
localhost
8.8.8.8

但是使用全局代理还是失败   参照更多配置修改了还是没啥头绪。

可以看到数据包到了trojan上 但是handshake failed  因为 Operation canceled
我猜测 Operation canceled 应该是  路由规则有问题？但是路由规则已经很简单了啊

**Comment by jmyz0455** [comment]
@paomuer 我看过你的配置跟我成功的配置没什么两样，你有用过 SwitchyOmega 测试你的 trojan 搭建成功了吗？如果没有，建议学我一样先排除 trojan 本身是不是可用的。
此外，我这个是 macOS 版本，不知道你的是不是 Windows 导致配置差异。

**Comment by paomuer** [comment]
@jmyz0455 
非常感谢，我也是macOS并且用过 SwitchyOmega测试了是ok的。
上面配置没问题，我找到问题了，因为本地还开了openVPN，路由规则跟mellow冲突了。暂时没找到共存的方法。

**Comment by jmyz0455** [comment]
@paomuer  openVPN 比 Trojan 或 V2ray 好用么？你关掉 openVPN 应该就不冲突了吧？
