### ISSUE TITLE
大神这个进程代理用来玩游戏会泄漏本地IP吗?

### ISSUE THREAD

**Issue by nic8888dsf** [mellow-io/mellow#181]
大神写的这个软件试用了下感觉功能很强大,之前用过proxifier,代理经常会失效,然后就要重装,第一次用这个软件不是很明白,这个进程代理是什么原理呀?网上搜了搜说tun是靠修改路由表来代理的,这个进程代理需要注意什么吗?

**Comment by nic8888dsf** [comment]
就是不用全局,如果用全局肯定没问题,我只代理游戏相关进程,其他都是直连,
[Endpoint]
Direct, builtin, freedom, domainStrategy=AsIs
rs, builtin, socks, address=127.0.0.1, port=1080
[RoutingRule]
GEOIP, private, Direct
PROCESS-NAME, RuneScape.exe, rs
PROCESS-NAME, rs2client.exe, rs
PROCESS-NAME, JagexLauncher.exe, rs


配置文件是这样的,连接记录看游戏应该是走了代理,然后电脑其他都是直连,但是连接记录里有很多unknown  process,不是很明白所以来问问..

**Comment by eycorsican** [comment]
https://github.com/mellow-io/mellow#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%9C%A8-sessions-%E4%B8%AD%E6%9C%89%E4%BA%9B%E8%AF%B7%E6%B1%82%E6%98%BE%E7%A4%BA%E8%BF%9B%E7%A8%8B%E5%90%8D%E7%A7%B0%E4%B8%BA-unknown-process

游戏的 UDP 会话时间一般都比较长，可以获得其进程

**Comment by nic8888dsf** [comment]
是一开始就能拦截到流量吗?还是需要流量多点识别之后才能拦截流量?就是最开始的时候会泄漏本地IP出去吗?主要是TCP流量,应该没有UDP流量因为proxifier不支持udp也能玩

**Comment by eycorsican** [comment]
没有这种泄漏。

不是拦截进程流量，而是流量来了之后识别是哪个进程发送的，再根据规则分配到哪个代理出口：https://github.com/mellow-io/mellow#mellow-%E5%B7%A5%E4%BD%9C%E6%B5%81%E7%A8%8B%E5%9B%BE

**Comment by nic8888dsf** [comment]
好的谢谢,我找了很久这类软件了,这样的开源软件真的少
