### ISSUE TITLE
widows标准账户下core无法获取所有进程名称

### ISSUE THREAD

**Issue by zhanxk** [mellow-io/mellow#184]
### 使用操作系统类型以及版本

windows 10 1909

### 使用 Mellow 版本

v0.1.16

### 问题描述
我用标准账户运行windows，mellow 配合clash for windows 使用，当使用标准账户运行clash时，mellow并不能获取到clash的进程，导致回环卡死，只有以administator运行clash，mellow才能获取到clash进程，程序运行正常。 看了下代码，获取进程的部分应该在core里面，希望能够改进下。

### 相关配置

{

  "outbounds": [
    {
      "protocol": "socks",
      "tag": "ClashX",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 7891
          }
        ]
      }
    },
     {
      "protocol": "freedom",
  //    "settings": {
  //      "domainStrategy": "UseIP"
  //    },
      "tag": "direct"
    },
    {
      "protocol": "shadowsocks",
      "settings": {
        "servers": [
          {
            "address": "xxxxx", // Shadowsocks 的服务器地址
            "method": "aes-128-gcm", // Shadowsocks 的加密方式
            "ota": false, // 是否开启 OTA，true 为开启
            "password": "xxxxxxxxxxxxxx", // Shadowsocks 的密码
            "port": xxxxxx,
            "network": "tcp,udp"
          }
        ]
      },
      "tag": "UdpProxy"
    }
  ],
  "routing": {
    "rules": [
       {
        "type": "field",
        "outboundTag": "direct",
        "app": [
          "clash*",
          "Clash*"
        ]
      },
      {
        "type": "field",
         "ip": [
             "geoip:cn",
             "224.0.0.0/4",
             "240.0.0.0/4",
             "10.255.0.0/24"
         ],
        "outboundTag": "direct", // freedom 的 tag
        "network": "udp"
      },
       {
        "type": "field",
        "outboundTag": "UdpProxy", // freedom 的 tag
        "network": "udp"
      },
      {
        "type": "field",
        "outboundTag": "ClashX",
        "ip": [
          "0.0.0.0/0",
          "::/0"
        ]
      }
    ],
    "domainStrategy": "AsIs"
  }
}

### 相关日志、截图

![image](https://user-images.githubusercontent.com/11792815/77813758-1e380c00-70e6-11ea-9085-bb21fe6ee178.png)

**Comment by liangxyz** [comment]
请问 "protocol": "shadowsocks"，按理说mellow作为透明代理，cfw和clash作为前置socks5代理就够了呀，不太明白为什么要添加ss服务器呢？

**Comment by zhanxk** [comment]
> 请问 "protocol": "shadowsocks"，按理说mellow作为透明代理，cfw和clash作为前置socks5代理就够了呀，不太明白为什么要添加ss服务器呢？

因为我买了俄罗斯的服务器，不支持telegram的，所以我把自己的telegram流量转发到shadowsocks的服务器中，这样我的clash切换到俄罗斯服务器时候，能够不影响telegram的运行
 {
         "type": "field",
          "ip": [
           "91.108.4.0/22",
           "91.108.8.0/22",
 "91.108.12.0/22",
 "91.108.16.0/22",
 "91.108.56.0/22",
 "149.154.160.0/22",
 "149.154.164.0/22",
 "149.154.168.0/22",
 "149.154.172.0/22"
          ],
         "outboundTag": "TelegramProxy" 
        
       },
      {
        "type": "field",
        "outboundTag": "ClashX",
        "ip": [
          "0.0.0.0/0",
          "::/0"
        ]
      }
    ],

**Comment by liangxyz** [comment]
感谢解答，我懂了。我正好想找mellow和clash配合的配置，谢谢你的分享

**Comment by liangxyz** [comment]
你好，再次请教下
`"type": "field",
			"ip": [
				"geoip:cn",
				"224.0.0.0/4",
				"240.0.0.0/4",
				"10.255.0.0/24"
			],
			"outboundTag": "direct", // freedom 的 tag
			"network": "udp"`
这一段是为了解决clash的fake-ip dns直连的吗？

**Comment by zhanxk** [comment]
1. 这是mellow的完整配置，因为我的clash里面的服务器使用的是shadowsocks配合v2ray-plugin的http混淆，所以只能使用fake-dns配置，mellow必须只能开启fake-dns的
{
  // "dns": {
  //   "servers": [
  //     {
  //       "address": "8.8.8.8",
  //       "port": 53,
  //       "domains": [
  //         "geosite:geolocation-!cn",
  //         "domain:google.com"
  //       ]
  //     }
  //   ],
  //   "hosts": {
  //     "download.microsoft.com": "xxxxx"
  //   }
  // },
  "outbounds": [
    {
      "protocol": "socks",
      "tag": "ClashX",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 7891
          }
        ]
      }
    },
    // {
    //   "protocol": "dns",
    //   "tag": "Dns-Out",
    //   "settings": {}
    // },
     {
      "protocol": "freedom",
  //    "settings": {
  //      "domainStrategy": "UseIP"
  //    },
      "tag": "direct"
    },
    {
      "protocol": "shadowsocks",
      "settings": {
        "servers": [
          {
            "address": "xxxxxcom", // Shadowsocks 的服务器地址
            "method": "aes-128-gcm", // Shadowsocks 的加密方式
            "ota": false, // 是否开启 OTA，true 为开启
            "password": "xxxxxxxxxxxxxx", // Shadowsocks 的密码
            "port": 1062,
            "network": "tcp,udp"
          }
        ]
      },
      "tag": "TelegramProxy"
    }
  ],
  "routing": {
    "rules": [
       {
        "type": "field",
        "outboundTag": "direct",
        "app": [
          "clash*",
          "Clash*"
        ]
      },
      // {
      //   "type": "field",
      //   "outboundTag": "Dns-Out",
      //   "inboundTag": [
      //     "tun2socks"
      //   ],
      //   "network": "udp",
      //   "port": 53
      // },
     //   {
     //    "type": "field",
     //     "outboundTag": "direct",
     //     "ip": [
     //       "geoip:cn"
     //     ],
     //     "network": "udp"
     // },
      //  {
      //   "type": "field",
      //   "outboundTag": "direct",
      //   "domain": ["geosite:cn"]
      // },
      //   {
      //   "type": "field",
      //   "outboundTag": "direct",
      //   "ip": [
      //     "geoip:cn"
      //   ]
      // },
      {
        "type": "field",
         "ip": [
             "geoip:cn",
             "224.0.0.0/4",
             "240.0.0.0/4",
             "10.255.0.0/24"
         ],
        "outboundTag": "direct", // freedom 的 tag
        "network": "udp"
      },
       {
         "type": "field",
          "ip": [
           "91.108.4.0/22",
           "91.108.8.0/22",
 "91.108.12.0/22",
 "91.108.16.0/22",
 "91.108.56.0/22",
 "149.154.160.0/22",
 "149.154.164.0/22",
 "149.154.168.0/22",
 "149.154.172.0/22"
          ],
         "outboundTag": "TelegramProxy" 
        
       },
      {
        "type": "field",
        "outboundTag": "ClashX",
        "ip": [
          "0.0.0.0/0",
          "::/0"
        ]
      }
    ],
    "domainStrategy": "AsIs"
  }
}

2. 这一段是为了解决clash的fake-ip dns直连的吗？ 这里面的似乎是广播的udp包吧，只是手贱，删除吧，没啥用的，除非你要打游戏，可以设置下拦截代理的udp的

3.  我以前透明代理用的是hyper-v配合openwrt加clash的，但是每次启动比较麻烦，而且hyper-v影响网速，还是mellow配置clash比较方便的

**Comment by liangxyz** [comment]
太感谢你了，我去参考下
