### ISSUE TITLE
Windows下建议改用PowerShell修改路由表

### ISSUE THREAD

**Issue by a86913179** [mellow-io/mellow#193]
### 使用操作系统类型以及版本

Windows 10 Pro x64

### 使用 Mellow 版本

0.1.17

### 相关日志、截图

建议使用PowerShell添加路由表，效果比`route add`好，而且可以删除指定TAP的路由，而不用删除全部0.0.0.0/0，即使2条0.0.0.0/0的路由metric都为0，但是TAP的网卡metric是0，比WAN的25优先级要高，`route print`可以看到**最终metric=路由metric+网卡metric**，所以流量还是会走TAP，根据我反复测试是能正常使用的，而且原来的命令删除所有0.0.0.0/0的时候会出现短暂的断网，现在这样是无缝切换。

**config_route.bat:**
```
set TUN_GW=%1
for /f %%a in ('PowerShell -Command "& {Get-NetAdapter -InterfaceDescription *TAP* | Select-Object -ExpandProperty InterfaceAlias}"') do (set TAP=%%a)
for /f %%b in ('PowerShell -Command "& {Get-NetRoute -DestinationPrefix 0.0.0.0/0 -InterfaceMetric 25 | Select-Object -ExpandProperty InterfaceAlias}"') do (set WAN=%%b)

PowerShell -Command "& {New-NetRoute -DestinationPrefix 0.0.0.0/0 -InterfaceAlias %TAP% -NextHop %TUN_GW% -RouteMetric 0 -PolicyStore ActiveStore -Confirm:$False}"
PowerShell -Command "& {Set-NetIPInterface -InterfaceAlias %WAN% -AddressFamily IPv6 -RouterDiscovery Disabled}"
PowerShell -Command "& {Clear-DnsClientCache}"
```

**recover_route.bat:**
```
set ORIG_GW=%1
for /f %%a in ('PowerShell -Command "& {Get-NetAdapter -InterfaceDescription *TAP* | Select-Object -ExpandProperty InterfaceAlias}"') do (set TAP=%%a)
for /f %%b in ('PowerShell -Command "& {Get-NetRoute -DestinationPrefix 0.0.0.0/0 -InterfaceMetric 25 | Select-Object -ExpandProperty InterfaceAlias}"') do (set WAN=%%b)

PowerShell -Command "& {Remove-NetRoute -InterfaceAlias %TAP% -Confirm:$False}"
PowerShell -Command "& {Set-NetIPInterface -InterfaceAlias %WAN% -AddressFamily IPv6 -RouterDiscovery Enabled}"
PowerShell -Command "& {Clear-DnsClientCache}"
```

![image](https://user-images.githubusercontent.com/23069451/78387439-ebc06e80-7611-11ea-91af-628609118074.png)

![image](https://user-images.githubusercontent.com/23069451/78388618-e5cb8d00-7613-11ea-9eaa-b2ed18b03926.png)

有2行PowerShell是开关主网卡IPV6的路由器发现功能，mellow启动会关闭，退出后mellow开启，这波操作是因为实测mellow用WFP拦截了IPV6流量后，打开网站速度很慢，DNS解析也很慢，我认为原因可能是尝试去连接IPV6地址，超时后才会去访问IPV4地址，所以索性启动mellow就把网卡的IPV6路由器发现关掉，取消::/0的路由，反正也用不了。关掉之后访问速度和DNS解析速度快了很多。本来是想直接删掉IPV6的默认路由::/0，我试过把IgnoreDefaultRoutes功能打开再删除，但是删完发现默认路由::/0还是会自动加回来，然后就试试RouterDiscovery，看来是这个功能一直添加::/0的路由。一开始还想到关闭网卡的IPV6协议，但是一开一关，会向路由器DHCP重复申请IPV6。用RouterDiscovery就不会重复申请IPV6地址了。

最后建议把所有网卡metric恢复到默认的自动，防止有其他软件修改过网卡，导致另外2个batch脚本无法获取正确参数，然后把TAP网卡权重改成0，优先级是最高的：
**ensure_tap_device.bat:**
```
echo Set all adapters metric to auto.
PowerShell -Command "& {Set-NetIPInterface -InterfaceAlias * -AutomaticMetric Enabled}"

echo Set TAP adapter metric to 0.
PowerShell -Command "& {Set-NetIPInterface -InterfaceAlias %DEVICE_NAME% -InterfaceMetric 0}"
```

**Comment by a86913179** [comment]
强迫症的我，最终还是没忍住，全改成PowerShell了，舒服了。

**config_route.bat:**
```
set TUN_GW=%1
set ORIG_GW=%2
for /f %%a in ('PowerShell -Command "& {Get-NetAdapter -InterfaceDescription *TAP* | Select-Object -ExpandProperty Name}"') do (set TAP=%%a)
for /f %%b in ('PowerShell -Command "& {Get-NetRoute -DestinationPrefix 0.0.0.0/0 | Select-Object -ExpandProperty InterfaceAlias}"') do (set WAN=%%b)

PowerShell -Command "& {Remove-NetRoute -DestinationPrefix 0.0.0.0/0 -Confirm:$False}"
PowerShell -Command "& {New-NetRoute -DestinationPrefix 0.0.0.0/0 -InterfaceAlias %TAP% -NextHop %TUN_GW% -RouteMetric 0 -PolicyStore ActiveStore -Confirm:$False}"
PowerShell -Command "& {New-NetRoute -DestinationPrefix 0.0.0.0/0 -InterfaceAlias %WAN% -NextHop %ORIG_GW% -RouteMetric 0 -PolicyStore ActiveStore -Confirm:$False}"
PowerShell -Command "& {Set-NetIPInterface -InterfaceAlias %WAN% -AddressFamily IPv6 -RouterDiscovery Disabled}"
PowerShell -Command "& {Clear-DnsClientCache}"
```

**recover_route.bat:**
```
set ORIG_GW=%1
for /f %%a in ('PowerShell -Command "& {Get-NetRoute -DestinationPrefix 0.0.0.0/0 | Select-Object -ExpandProperty InterfaceAlias}"') do (set WAN=%%a)

PowerShell -Command "& {Remove-NetRoute -DestinationPrefix 0.0.0.0/0 -Confirm:$False}"
PowerShell -Command "& {New-NetRoute -DestinationPrefix 0.0.0.0/0 -InterfaceAlias %WAN% -NextHop %ORIG_GW% -RouteMetric 0 -PolicyStore ActiveStore -Confirm:$False}"
PowerShell -Command "& {Set-NetIPInterface -InterfaceAlias %WAN% -AddressFamily IPv6 -RouterDiscovery Enabled}"
PowerShell -Command "& {Clear-DnsClientCache}"
```

IPV6换了种方式，不再是关闭所有网卡的IPV6，而是把主要网卡IPV6的路由发现功能关闭了，退出mellow再打开，这样就不会添加默认路由::/0了，ignoredefaultroutes我关了再删除::/0发现还是会自动加回来。如果想干净杀绝可以用1楼那条，关闭所有网卡IPV6，退出mellow再打开。

**Comment by a86913179** [comment]
#195

**Comment by eycorsican** [comment]
```
for /f %%b in ('PowerShell -Command "& {Get-NetRoute -DestinationPrefix 0.0.0.0/0 -InterfaceMetric 25 | Select-Object -ExpandProperty InterfaceAlias}"') do (set WAN=%%b)
```

用 metric 25 这条件找原默认网卡是否不太合适？就算已经把所有网卡的 metric 都重置为 auto，也不一定就是 25，文档也没提到会是某个特定值：https://docs.microsoft.com/en-us/powershell/module/nettcpip/set-netipinterface?view=win10-ps

另外删除所有默认路由导致短暂的断网，这个断网有时候是需要的，因为如果不这样做，有些在启动 Mellow 前已经通过原网关建立起来的 TCP 连接，在 Mellow 启动之后还会被继续使用，就是说这些连接绕过 Mellow 了。（这点我没验证，理论上应该是这样的）

**Comment by a86913179** [comment]
> ```
> for /f %%b in ('PowerShell -Command "& {Get-NetRoute -DestinationPrefix 0.0.0.0/0 -InterfaceMetric 25 | Select-Object -ExpandProperty InterfaceAlias}"') do (set WAN=%%b)
> ```
> 
> 用 metric 25 这条件找原默认网卡是否不太合适？就算已经把所有网卡的 metric 都重置为 auto，也不一定就是 25，文档也没提到会是某个特定值：https://docs.microsoft.com/en-us/powershell/module/nettcpip/set-netipinterface?view=win10-ps
> 
> 另外删除所有默认路由导致短暂的断网，这个断网有时候是需要的，因为如果不这样做，有些在启动 Mellow 前已经通过原网关建立起来的 TCP 连接，在 Mellow 启动之后还会被继续使用，就是说这些连接绕过 Mellow 了。（这点我没验证，理论上应该是这样的）

我在一台笔记本和一台台式机上测试过，有线网卡和无线网卡还有开热点用的虚拟无线网卡的metric设为自动都是25，Loopback都是75。网卡产商也不一样，笔记本有线是Realtek，无线是Intel，台式机有线是Intel。

至于删除默认路由断网是为了断开原来的TCP连接我倒是没想到，我觉得原来的连接就应该让他继续，等它自己结束就好，反正有超时，超时到了发起新连接就会走mellow了，或者重新启动程序。有时候会遇到这种情况：我在用SSH登陆VPS搞东西，但同时又想让有个程序走代理，这时候如果启动mellow，突然把我的SSH断了，就无语了。我还得等VPS上东西弄好再去开mellow。不过你也可以按照你的想法来。

按照你的思路的话就是我改的较早版本，就是完全按原来命令的步骤来，只是修改了命令程序：https://github.com/mellow-io/mellow/pull/195/files

**Comment by eycorsican** [comment]
按这个 auto metric 的解释就不能用它来做条件了，比如说 win7 网卡是 100Mpbs（这个应该很常见），auto metric 就是 20。

为什么只关 WAN 的 IPv6 而不是全部适配器都关了？或者说只关 TAP 的 IPv6 可以解决一开始访问慢的问题不？这样就不需要找 WAN 适配器了。

留着原来 TCP 连接不断开倒也没什么，只是如果有个配置选项会更好。

**Comment by a86913179** [comment]
> 按这个 auto metric 的解释就不能用它来做条件了，比如说 win7 网卡是 100Mpbs（这个应该很常见），auto metric 就是 20。
> 
> 为什么只关 WAN 的 IPv6 而不是全部适配器都关了？或者说只关 TAP 的 IPv6 可以解决一开始访问慢的问题不？这样就不需要找 WAN 适配器了。
> 
> 留着原来 TCP 连接不断开倒也没什么，只是如果有个配置选项会更好。

按照这个文档确实不能用metric来作为条件，我在本机上看到TAP速率是100，metric自动后是35。

刚刚测试关闭了TAP网卡的IPV6，然后把那2行PowerShell注释了，访问速度还是慢，因为路由表里IPv6的默认路由::/0走的还是主网卡，而不是走的TAP网卡，所以关不关TAP的IPV6不影响。我想还是关闭所有网卡的IPV6路由器发现功能比较好吧。这样就不用去找主网卡的适配器名称。

`PowerShell -Command "& {Set-NetIPInterface -InterfaceAlias * -AddressFamily IPv6 -RouterDiscovery Disabled}"`

TCP连接不适合断开还有种情况就是比如你在下载一个东西，下到一半了已经，这时候如果打开mellow做其他事，而mellow又把原来的连接断开就很麻烦。不过配置选项这个我无能为力了，哈哈。

**Comment by a86913179** [comment]
如果想更精简命令，可以把3个batch里的` -InterfaceAlias *`去掉，因为是修改所有网卡，所以有没有这个参数效果都一样。

**Comment by a86913179** [comment]
其实我觉得在main.js里把config_route.bat的传入参数tunGw, origGw改为tunGw, tunName，recover_route.bat的传入参数origGw改为tunName，然后就可以直接在batch里面set比较好，因为有些人的电脑没有卸载多余的TAP网卡，而直接安装mellow
```
for /f %%a in ('PowerShell -Command "& {Get-NetAdapter -InterfaceDescription *TAP* | Select-Object -ExpandProperty InterfaceAlias}"') do (set TAP=%%a)
```
这条命令就无法正确set到mellow-tap0了。我是把其他软件和网卡都卸载干净才装mellow的，不排除有些人同时安装多个TAP代理软件。之前没考虑到这点，抱歉！但这个修改需要重新编译发布才能生效。

**config_route.bat**改成这样：

```
set TUN_GW=%1
set DEVICE_NAME=%2

PowerShell -Command "& {New-NetRoute -DestinationPrefix 0.0.0.0/0 -InterfaceAlias %DEVICE_NAME% -NextHop %TUN_GW% -RouteMetric 0 -PolicyStore ActiveStore -Confirm:$False}"
PowerShell -Command "& {Set-NetIPInterface -AddressFamily IPv6 -RouterDiscovery Disabled}"
PowerShell -Command "& {Clear-DnsClientCache}"
```

**recover_route.bat**改成这样：

```
set DEVICE_NAME=%1

PowerShell -Command "& {Remove-NetRoute -InterfaceAlias %DEVICE_NAME% -Confirm:$False}"
PowerShell -Command "& {Set-NetIPInterface -AddressFamily IPv6 -RouterDiscovery Enabled}"
PowerShell -Command "& {Clear-DnsClientCache}"
```

**ensure_tap_device.bat**保持不变：

```
echo Set all adapters metric to auto.
PowerShell -Command "& {Set-NetIPInterface -AutomaticMetric Enabled}"

echo Set TAP adapter metric to 0.
PowerShell -Command "& {Set-NetIPInterface -InterfaceAlias %DEVICE_NAME% -InterfaceMetric 0}"
```

**Comment by AlbertWang2018** [comment]
我优化了一下，这是我用的脚本：
$a=(Get-NetAdapter -InterfaceDescription *pan*).ifIndex 
#$a
$b=Get-NetRoute -DestinationPrefix 0.0.0.0/0 -ifindex $a
#$b
$c=(Get-NetIPAddress -InterfaceIndex $a).IPAddress
$d="route change 0.0.0.0 mask 0.0.0.0 $c metric 20 if $a"
$d
cmd /c $d
