### ISSUE TITLE
程序在未连接时的图标颜色太暗，导致误认为程序没有启动

### ISSUE THREAD

**Issue by ow1wo** [mellow-io/mellow#202]
### 使用操作系统类型以及版本

windows 10

情况如下图：

![heightmap7](https://user-images.githubusercontent.com/44597884/78458905-948ccd80-76e7-11ea-9491-600f10b9931d.png)

因为我的windows系统任务栏颜色是深蓝色的，和这个程序的图标十分接近，导致我以为程序没有启动。查看任务管理器又发现在，log也正常，但是一直找不到任务栏上的图标。卸载安装了好多次，才发现是图标太暗看不清。折腾了快一个小时。。。

希望能把图标颜色改一下，在未连接时搞个显眼一些的图标底色，确保任何时候都能看到图标

**Comment by a86913179** [comment]
https://github.com/mellow-io/mellow/issues/221 https://github.com/mellow-io/mellow/issues/173
