### ISSUE TITLE
无法访问oculus.com

### ISSUE THREAD

**Issue by thesunfei** [mellow-io/mellow#208]
### 使用操作系统类型以及版本

WIN10

### 使用 Mellow 版本

0.1.18

### 问题描述
使用mellow连接Trojan无法访问oculus.com，其他被墙网站可以正常访问。
使用switchyOmega连接Trojan可以访问oculus.com。
换了其他电脑也有同样的问题。

### 相关配置
{
  "outbounds": [{
      "tag": "Socks-Out",
      "protocol": "socks",
      "settings": {
        "servers": [{
          "address": "127.0.0.1",
          "port": 1000
        }]
      }
    },
    {
      "protocol": "freedom",
      "tag": "Direct",
      "settings": {
        "domainStrategy": "UseIP"
      }
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "outboundTag": "Direct",
        "ip": [
          "geoip:private",
          "***.***.***.***\/0"
        ]
      },
      {
        "type": "field",
        "outboundTag": "Socks-Out",
        "network": "tcp,udp"
      }
    ]
  }
}

### 相关日志、截图

![image](https://user-images.githubusercontent.com/7395840/78504379-64a10100-779f-11ea-8101-7eb53490e807.png)

**Comment by a86913179** [comment]
我这边测试正常，你这个config没有配置trojan进程直连，导致进入loop
