### ISSUE TITLE
开启系统代理后，端口号可否自己修改

### ISSUE THREAD

**Issue by sagexy** [mellow-io/mellow#219]
如题，希望系统代理可以自己修改端口号，建议性问题，非bug 😁

**Comment by foxundermoon** [comment]
core 监听的  6001 端口吗？
 我也在找这个配置项， 端口和其他的冲突了

**Comment by sagexy** [comment]
> core 监听的 6001 端口吗？
> 我也在找这个配置项， 端口和其他的冲突了

我指的是修改以下中的 systemProxyHttpPort，systemProxySocksPort端口号 没找到可以自己配置此处的端口号，只能通过修改源码后自己编译
https://github.com/mellow-io/mellow/blob/f130549fc7d63c1bc39e15e00e2c6b9b883a90ae/src/main.js#L39
