### ISSUE TITLE
v0.1.18和v0.1.19在win10里打不开

### ISSUE THREAD

**Issue by xiexie720** [mellow-io/mellow#221]
### 使用操作系统类型以及版本
win10企业版2016长期服务版64位系统

### 使用 Mellow 版本
v0.1.18和v0.1.19

### 问题描述

双击软件后能看到任务管理器里有三个mellow进程，但是任务栏不显示托盘图标，也不显示任何界面。重启电脑也没用。

**Comment by a86913179** [comment]
Related to: https://github.com/mellow-io/mellow/issues/173

**Comment by zhangwangcoder** [comment]
> Related to: #173

第一次使用，同样的问题，麻烦开发者修改一下颜色
