### ISSUE TITLE
mellow支持添加http代理吗？

### ISSUE THREAD

**Issue by haha-0000** [mellow-io/mellow#225]
mellow除了支持ss、vmess还能支持http代理吗？我试了好像不可以

**Comment by RonaldinhoL** [comment]
v2ray支持http，mellow使用的v2ray肯定也支持http的。

**Comment by haha-0000** [comment]
你好，其实我指的是本地搭建的http代理，不是从mellow本身创建的

**Comment by laggardkernel** [comment]
使用本地代理会有回环问题。必须同时关闭 Domain Sniffing 和 Fake DNS。 https://github.com/mellow-io/mellow/issues/52
