### ISSUE TITLE
绕过CN的配置某些网站依然走代理

### ISSUE THREAD

**Issue by 39499740** [mellow-io/mellow#235]
### 使用操作系统类型以及版本
Macos 10.15.4 (19E287)

### 使用 Mellow 版本
0.1.19

### 问题描述

我使用的Readme里面提示的绕过CN配置

![image](https://user-images.githubusercontent.com/29425312/80301813-dd144400-87d8-11ea-8c3d-37abc242fc3b.png)

目前发现登录pay.sdo.com的时候走了代理，请问这里是配置问题么？

### 相关日志、截图

![image](https://user-images.githubusercontent.com/29425312/80301748-83ac1500-87d8-11ea-9fb3-8217e76de6a8.png)

**Comment by a86913179** [comment]
配置添加
```
[Routing]
domainStrategy = IPIfNonMatch
```

**Comment by 39499740** [comment]
谢谢，解决了~
