### ISSUE TITLE
无法打开‘core'，因为无法验证开发者

### ISSUE THREAD

**Issue by Dr-Bluemond** [mellow-io/mellow#236]
### 使用操作系统类型以及版本
macOS Catalina 10.15.4

### 使用 Mellow 版本
v0.1.19

### 问题描述
每次重新启动计算机都会弹出“无法打开‘core'，因为无法验证开发者”这样的弹窗，然后mellow就会报错，每次都需要在设置中点击允许，特别的麻烦，这个问题可以克服掉吗？

### 问题复现步骤
在mac较高版本安装Mellow，第一次运行也会弹出“无法打开core”，重启也会弹出“无法打开core”

### 相关日志、截图
![截屏2020-04-26 下午11 15 26](https://user-images.githubusercontent.com/8200165/80311911-ee7b4180-8814-11ea-8a16-35c202c5710b.png)

**Comment by chenshengzhi** [comment]
同问, 需要自己编译吗?

**Comment by Dr-Bluemond** [comment]
新版本v0.1.21无此问题，感谢作者修复
