### ISSUE TITLE
请优化配置项文档

### ISSUE THREAD

**Issue by RickoNoNo3** [mellow-io/mellow#242]
希望文档不仅仅是源码和example的形式, 而是把各个关键字能够取什么值, 何时起效, 相互之间的关系列出来.

比如Dns, DnsServer, DnsRule, DnsHost之间的程序逻辑?
再比如rule type的取值, example列出来的就是所有的取值了吗? 分别代表什么意思? DOMAIN和DOMAIN-FULL的区别是?
每种rule type的filter又是什么规则? 比如 `NETWORK, udp:tcp, Direct` 这句中 udp:tcp 的意思是?

另外geofile里能取什么值也应该给个[传送门](https://github.com/v2ray/domain-list-community)吧

---------

虽然我差不多弄懂了, 但是...全是扣代码扣懂得, 令人头秃 QAQ

**Comment by stevennight** [comment]
大佬弄懂了么，想设置一些host域名访问127.0.0.1（DnsHost）似乎没有生效，不是这么用的么。QAQ

**Comment by stevennight** [comment]
大佬弄懂了么，想设置一些host域名访问127.0.0.1（DnsHost）似乎没有生效，不是这么用的么。QAQ

**Comment by sagasm** [comment]
参考:
https://github.com/cwxyz007/v2ray-config-json-schema
https://guide.v2fly.org/
