### ISSUE TITLE
请求支持配置systemDns

### ISSUE THREAD

**Issue by MonwF** [mellow-io/mellow#243]
### 使用操作系统类型以及版本
mac os 10.15.3

### 使用 Mellow 版本
0.1.19

### 问题描述
默认系统dns设置为114.114.114.114和`8.8.8.8`，chrome会优先使用8.8.8.8的doh去解析dns。这样导致域名解析无法sniff，而且内部域名(如aaa.com) 想用内部dns解析都没法做到，因为公共dns无法解析此类域名

**Comment by MonwF** [comment]
编辑 `~/Library/Application\ Support/Mellow/preference.json` 修改了

**Comment by MonwF** [comment]
> 另外，我也遇到一个在使用 mellow 时有关 DNS 的问题。我在 mac 上使用本地 dns 作为解析服务，因此mac 系统的 dns 地址更改为 127.0.0.1，问题来了，每次使用 mellow 时，我的系统 dns 被改为其他，这是为什么呢？

只要默认dns是私有ip，被会被替换为114和4个8，这样才方便进行dns拦截

**Comment by opengit** [comment]
> 编辑 `~/Library/Application\ Support/Mellow/preference.json` 修改了

将文件`preference.json`修改后，还要将文件设置为只读，不然会被覆盖。望周知~
