### ISSUE TITLE
如何更新V2Ray Core？

### ISSUE THREAD

**Issue by MamaShip** [mellow-io/mellow#252]
### 使用操作系统类型以及版本
win10

### 使用 Mellow 版本
v0.1.19

### 问题描述
有更新 V2Ray Core 的需求

### 问题复现步骤
无关

### 相关配置
无关

### 相关日志、截图
无关

目前已知 v4.23.2 之前版本的 V2Ray Core 存在bug，导致流量特征会被精准识别。

https://github.com/v2ray/v2ray-core/issues/2518

https://github.com/v2ray/discussion/issues/704

想请教 Mellow 的 core 文件是否就是 v2ray-core 发布的可执行文件？用户能否直接替换？

如果不能，（我）作为开发者有什么方式可以帮忙更新 Core 吗？

**Comment by MamaShip** [comment]
@eycorsican

**Comment by zhuzeitou** [comment]
core应该是go-tun2socks带有v2ray功能的未开源版本吧
目前暂时可以使用本地另起v2ray客户端+socks inbound，把mellow的outbound设成对应socks的方式
