### ISSUE TITLE
Mellow 启动导致WSL2无法上网

### ISSUE THREAD

**Issue by blue7wings** [mellow-io/mellow#255]
### 使用操作系统类型以及版本

版本：Windows 10 专业版
版本号：2004

### 使用 Mellow 版本

v0.1.19

### 问题描述

只要mellow打开，WSL就无法链接网络

### 问题复现步骤

ping: www.baidu.com: Temporary failure in name resolution

### 相关配置

[Endpoint]
Proxy, vmess1, vmess1://2b246cab-dc0f-4d38-8893-fc4e7c48972b@example:7722?network=tcp

Direct, builtin, freedom, domainStrategy=UseIP
Dns-Out, builtin, dns

[RoutingRule]
DOMAIN-KEYWORD, geosite:cn, Direct
GEOIP, cn, Direct
GEOIP, private, Direct
FINAL, Proxy

[Dns]
hijack = Dns-Out

[DnsServer]
localhost
8.8.8.8

**Comment by zyw1998nuaa** [comment]
可以使用line的电脑端客户端吗？，我电脑的是Windows 10

**Comment by VincentFF** [comment]
我测试了一下, 使用ping不行, 但是使用curl可以. 所以可能是ICMP协议不行， 但tcp协议是肯定可以的。
希望开发者来解答一下这个问题。

**Comment by blue7wings** [comment]
> 我测试了一下, 使用ping不行, 但是使用curl可以. 所以可能是ICMP协议不行， 但tcp协议是肯定可以的。
> 希望开发者来解答一下这个问题。

应该是Tap网卡的问题，已经放弃折腾。改用v2ray + proxifer配合白名单的方式非常稳定和方便，[白名单规则下载](https://www.dropbox.com/s/uas69rfz8e8qy2v/proxifer%20whitelist%20config.ppx?dl=0)
