### ISSUE TITLE
win10移动热点开启，本机代理失效，连接热点的机器时也不能通过mellow实现透明代理

### ISSUE THREAD

**Issue by Xianbei233** [mellow-io/mellow#26]

**Comment by eycorsican** [comment]
我没条件测试

**Comment by Xianbei233** [comment]
> 我没条件测试

我测试了下，不仅不能代理连接热点的机器，连作为热点的本机也代理失效了

**Comment by ZZYSonny** [comment]
可以参考这个https://www.expressvpn.com/support/vpn-setup/share-vpn-connection-windows/
