### ISSUE TITLE
更新到 0.1.20 之后版本号还是 0.1.19。

### ISSUE THREAD

**Issue by TDL3** [mellow-io/mellow#271]
### 使用操作系统类型以及版本
Windows 10 2004

### 使用 Mellow 版本
0.1.20?

### 问题描述
更新到 0.1.20? 之后 About 中的版本号还是0.1.19。
Github lastest release 中的 0.1.20 tag 下文件名中的版本号是0.1.19。

### 相关日志、截图
![image](https://user-images.githubusercontent.com/29535697/88212862-8230a280-cc8a-11ea-937b-215b52dc8180.png)
![image](https://user-images.githubusercontent.com/29535697/88212880-8957b080-cc8a-11ea-9a41-7bd9b187f25a.png)
![image](https://user-images.githubusercontent.com/29535697/88212935-9eccda80-cc8a-11ea-8f1e-6b01f037589b.png)

**Comment by sagasm** [comment]
请问有电报群么
