### ISSUE TITLE
0.1.21无法安装

### ISSUE THREAD

**Issue by sagasm** [mellow-io/mellow#272]
### 使用操作系统类型以及版本
win10 x64

### 使用 Mellow 版本

0.1.21

### 问题描述
点击Mellow.Setup.0.1.21.exe后,安装进度卡在附图不动:

### 相关日志、截图

![TIM截图20200723095935](https://user-images.githubusercontent.com/14829950/88256910-13d1fb80-ccef-11ea-8042-98275538b93f.png)

**Comment by asiaso** [comment]
我也是win10 同样也安装的这个版本，我安装的时候没有问题。
