### ISSUE TITLE
How create TUN/TAP adapter with Socks5 to VirtualBox?

### ISSUE THREAD

**Issue by rabota07** [mellow-io/mellow#280]
1. 我在哪里可以得到这个程序的详细使用指南？
2. 我可以在配置文件中写哪些命令？
3. 根本不清楚如何使用程序？

**Comment by wppurking** [comment]
> 1. 我在哪里可以得到这个程序的详细使用指南？

这里是最简单的[全局代理的例子](https://github.com/mellow-io/mellow/blob/master/README.1.md#%E5%85%A8%E5%B1%80%E4%BB%A3%E7%90%86%E9%85%8D%E7%BD%AE), 这里是 [cn 与 private 不翻墙的例子](https://github.com/mellow-io/mellow/blob/master/README.1.md#%E7%AE%80%E5%8D%95%E9%85%8D%E7%BD%AE)
最简单的配置文件都在 readme 中.

> 2. 我可以在配置文件中写哪些命令？

这个是所有你能够在其中[写的命令](https://github.com/mellow-io/mellow/blob/master/README.1.md#%E6%9B%B4%E5%A4%9A%E9%85%8D%E7%BD%AE), 还要更详细要看代码中的 [spec 测试](https://github.com/mellow-io/mellow/blob/master/src/spec/conf_to_json.spec.js)

> 3. 根本不清楚如何使用程序？

整个应用的[流程架构图](https://github.com/mellow-io/mellow/blob/master/README.1.md#mellow-%E5%B7%A5%E4%BD%9C%E6%B5%81%E7%A8%8B%E5%9B%BE)在这里了, 已经很详细了. 最简单的时候也在 "[关于配置和启动](https://github.com/mellow-io/mellow/blob/master/README.1.md#%E5%85%B3%E4%BA%8E%E9%85%8D%E7%BD%AE%E5%92%8C%E5%90%AF%E5%8A%A8)" 中
