### ISSUE TITLE
断开连接后自动复原dns，如果电脑换了网，可能导致dns不匹配而断网

### ISSUE THREAD

**Issue by lwabish** [mellow-io/mellow#281]
### 使用操作系统类型以及版本

osx 10.15

### 使用 Mellow 版本

0.1.22

### 问题描述

mellow会记忆启动时的系统dns，在关闭连接后会自动填入记忆的dns，此时如果电脑换了网络，可能导致断网。此处是否可从代码逻辑或使用方法上进行优化 ，使得不需要每次切换网络还需要注意mellow导致的dns问题？

### 问题复现步骤

1. 在网络192.168.0.1/24中启动mellow，正常使用
2. 带着电脑去公司，此时网络为172.16.xxx，dns已经不是192.168.0.1
3. 在公司临时操作断开mellow，此时dns会设置为启动时的dns 192.168.0.1，导致断网

**Comment by jialanmo** [comment]
原来是这个问题，我说为什么换了个地方一启动mellow就可以上网，一关闭就不能，折腾了俩小时，差点重装系统😄。

**Comment by Jeffery-Song** [comment]
原来是这个问题。。感谢 手动重置DNS解决了。坐等fix
