### ISSUE TITLE
mellow-master cnpm run dlgeo is ERROR

### ISSUE THREAD

**Issue by ddy4633** [mellow-io/mellow#288]
### 使用操作系统类型以及版本

linux 

### 使用 Mellow 版本

master

### 问题描述

(mypy3) ➜  mellow-master cnpm run dlgeo                                                   

> Mellow@0.1.22 dlgeo /tools/mellow-master
> node scripts/dl_geo.js

Downloading https://github.com/v2ray/domain-list-community/releases/latest/download/dlc.dat
Downloading https://web.archive.org/web/20191227182412/https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
(node:45671) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
(node:45671) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:45671) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 问题复现步骤

安装错误

**Comment by qq805005062** [comment]
@ddy4633 你的这个错误是怎么解决的，我也遇到相同的问题了

**Comment by ddy4633** [comment]
我放弃了，哈哈

**Comment by qq805005062** [comment]
@ddy4633 他们这个项目好像没人维护，问题都没人回答的
