### ISSUE TITLE
使用绕过CN的配置后，访问国内网站打开速度非常慢

### ISSUE THREAD

**Issue by 39499740** [mellow-io/mellow#289]
系统：macOS 10.15.6

Mellow：0.1.21

我使用如下配置
```
[Endpoint]
MyProxyServer, vmess1, vmess1://xxxxxxxxxxxxxxx
Direct, builtin, freedom, domainStrategy=UseIP
Dns-Out, builtin, dns

[RoutingRule]
DOMAIN-KEYWORD, geosite:cn, Direct
GEOIP, cn, Direct
GEOIP, private, Direct
FINAL, MyProxyServer

[Dns]
hijack = Dns-Out

[DnsServer]
localhost
8.8.8.8
[Routing]

domainStrategy = IPIfNonMatch
```

现在方位国内网站确实是直连，但是开启速度非常慢。
总结下来应该是第一次打开的时候特别慢，应该不是CSS和JS加载的问题，因为卡住的时候网页没有标题。
初步判断应该是DNS的时间过长。
但是这边我现在除了8.8.8.8，也会用国内的114.114.114.114,一样的慢。

例如，刚才开启qq.com，第一次需要白屏8秒，然后才出现标题。
第二次就是秒出

**Comment by automsen** [comment]
问题应该出现在dns，没有配置路由，国内的dns到国外去了

**Comment by 39499740** [comment]
> 问题应该出现在dns，没有配置路由，国内的dns到国外去了

我觉得也是这个问题，不过不知道怎么修改

**Comment by automsen** [comment]
GEOIP, cn, Direct  这个里面加上dns服务器的ip

**Comment by 39499740** [comment]
> GEOIP, cn, Direct 这个里面加上dns服务器的ip

GEOIP, cn, Direct, 114.114.114.114
这样么？

**Comment by skill7899** [comment]
> > GEOIP, cn, Direct 这个里面加上dns服务器的ip
> 
> GEOIP, cn, Direct, 114.114.114.114
> 这样么？

解决了吗？我跟你一样的情况
