### ISSUE TITLE
Windows下考虑使用Wireguard的WinTun？

### ISSUE THREAD

**Issue by ZZYSonny** [mellow-io/mellow#29]
https://www.wintun.net/
可能会比Tap Windows稳定一些？

**Comment by eycorsican** [comment]
有打算试下 wintun，因为它支持 IPv6。但你的意思是 tap-windows 不稳定？

**Comment by ZZYSonny** [comment]
就是感觉Tap的版本有点古老

**Comment by betterdoitnow** [comment]
Win10，使用mellow之后，发现直连网络延迟增加和下载性能降低，比如股票类软件连接服务器，延迟从原来的30ms左右增加到300ms+，关掉mellow之后恢复30ms。直连极限下载速度从70MB/s下降到30M-40MB左右。不知道上面这些是否和tap-windows有没有关系

**Comment by ZZYSonny** [comment]
@betterdoitnow 300ms可能是rule的问题，把发往国内的数据发到国外去了。

**Comment by betterdoitnow** [comment]
@ZZYSonny 这个rules里面肯定是走的direct啦。为了确认，我刚刚全局设成direct也是一样的效果

**Comment by eycorsican** [comment]
300延迟只影响非sniffing类型的请求，下版本会修复。吞吐量我没在win上测过也不清楚，高配linux上应该可达到上下行600Mbps/1.5Gbps

**Comment by betterdoitnow** [comment]
@eycorsican 谢谢回复，300延迟能修复就太棒了！另外，请看截图关于Win10上吞吐量的数据。另外我也留意了一下，打开Mellow之后测速时cpu没有占满，所以cpu本身应该并不是瓶颈。
![Win10 吞吐量](https://user-images.githubusercontent.com/25701030/65829211-614f2900-e2d5-11e9-8ee8-79a6657f5775.png)

**Comment by eycorsican** [comment]
@betterdoitnow v0.1.2 已经修了延迟问题，但 Windows 上还是会有 30ms 左右的延迟，是建立连接时的一次性消耗，耗在比如获取连接进程这样的操作上。

还测了下 Windows 的上下行，大概在 200Mbps/250Mbps，在 macOS 上测出 600Mbps/2.5Gbps，tap-windows 很可疑。。。

**Comment by betterdoitnow** [comment]
@eycorsican 刚刚试了一下v0.1.2，感觉良好，延迟正常了！你测试的Windows上下行吞吐量和我的差不多，哈哈，tap-windows.....

**Comment by ow1wo** [comment]
这个软件完美解决我的问题。折腾了各种方法，还是这个最简单，v2ray客户端都不用跑。太赞了！

**Comment by a86913179** [comment]
tap-windows的吞吐量确实是个问题，500Mbps的宽带，mellow设置qbittorrent直连，才到10MB/s，PING就开始丢包，网页也一直loading，关闭mellow，qbittorrent就能跑到66MB/s

**Comment by testermania** [comment]
https://lists.zx2c4.com/pipermail/wireguard/2019-September/004580.html

**Comment by liangxyz** [comment]
上次使用mellow的时候发现自动安装的tap网卡是100M的

**Comment by a86913179** [comment]
> 上次使用mellow的时候发现自动安装的tap网卡是100M的

目前repo里的驱动9.21.2（设备管理器显示9.0.0.21）是注册成物理网卡，但实际不是，所以变成100M，最新驱动9.24.2把TAP网卡注册成虚拟网卡，显示1Gbps。目前正在打算替换成最新的stable驱动。

**Comment by a86913179** [comment]
WINTUN_INSTALLER_X86_64:https://staging.openvpn.net/openvpn2/wintun-amd64.msi
WINTUN_INSTALLER_I686:https://staging.openvpn.net/openvpn2/wintun-x86.msi

@eycorsican openvpn已经生成单独的installer，可以编译个wintun版本测试下

**Comment by ZZYSonny** [comment]
我装了一下OpenVPN，然后把wintun设备名改成mellow-tap0，然后在Component ID那块报错了

**Comment by a86913179** [comment]
> 我装了一下OpenVPN，然后把wintun设备名改成mellow-tap0，然后在Component ID那块报错了
> 估计代码也要改的样子

因为Core.exe要找Component ID为tap0901的设备，core.exe没有开源，只能等作者改源码。

**Comment by eycorsican** [comment]
TUN 部分的代码就是这个：https://github.com/eycorsican/go-tun2socks/blob/master/tun/tun_windows.go

**Comment by a86913179** [comment]
> TUN 部分的代码就是这个：https://github.com/eycorsican/go-tun2socks/blob/master/tun/tun_windows.go

看下这样是否可行？
https://github.com/a86913179/go-tun2socks/commit/523c12255aacf49f61871a4f29bcf66378574a78

**Comment by a86913179** [comment]
Wintun的Component ID为wintun
