### ISSUE TITLE
搭配swichtyOmega使用的问题

### ISSUE THREAD

**Issue by versimilitude** [mellow-io/mellow#300]
请问一下，mellow开启后，能否在chrome中使用switchyOmega使用，这样偶尔查阅一些网站不能访问时，可以临时使用代理访问，不用每次修改配置文件或使用全局代理。谢谢。

**Comment by zhanxk** [comment]
可以这样使用的，但是很不方便，我是利用mellow将所有流量导入clash for windows中，这样查阅一些网站不能访问时，可以在clash中随时添加规则，立刻起作用，这样比较方便

**Comment by iHandle** [comment]
[详细说明](https://github.com/mellow-io/mellow/blob/master/README.1.md)中提到过关于要不要使用 Mellow的问题：
> 所以也很清楚的是，如果仅需要代理浏览器的请求，或者也不嫌麻烦为个别程序单独设置代理的话，是没必要使用 Mellow 的。

你这种情况只需要使用clash for windows，并且不开系统代理(system proxy)，chrome需要代理的时候只需要让switchOmega把流量发到localhost:7890
