### ISSUE TITLE
Win7无法连接代理，弹出错误弹窗

### ISSUE THREAD

**Issue by wnmwi** [mellow-io/mellow#307]
### 使用操作系统类型以及版本
windows 7 with sp1

### 使用 Mellow 版本
0.1.22

### 问题描述
连接代理错误，具体请看截图

### 问题复现步骤
安装好软件，设置好conf文件，点击连接，弹出错误

### 相关日志、截图
![360截图20201201222950148](https://user-images.githubusercontent.com/38154403/100753457-c136e780-3424-11eb-898b-536bdcf57cd9.jpg)

**Comment by summer-wu** [comment]
我这里是win10，也报这个错
![image](https://user-images.githubusercontent.com/2476434/106138600-4f221b00-61a7-11eb-812e-404cb7c31816.png)
