### ISSUE TITLE
请问转发进程级别的网络流量的大概实现思路是什么？

### ISSUE THREAD

**Issue by tangrenzhi** [mellow-io/mellow#310]
本人使用Python用Tap的方式实现了TCP和UDP的全局透明代理，目前是使用配置路由表的方式控制流量转发到代理，针对某个进程流量进行代理，查了许多资料更多的是要与windows api打交道，如果方便告知的话，请问本软件的大概用到的技术是什么呢？万分感谢！

**Comment by eycorsican** [comment]
基于源地址策略路由 +  https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getextendedtcptable

**Comment by tangrenzhi** [comment]
> 基于源地址策略路由 + https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getextendedtcptable

非常谢谢！
