### ISSUE TITLE
shadowsocks 协议代理无效？

### ISSUE THREAD

**Issue by laggardkernel** [mellow-io/mellow#54]
环境

- 系统 macOS 10.13.6
- Mellow 0.1.6

尝试使用如下格式 shadowsocks 协议代理无法连接网络，

```
Test, ss, ss://chacha20-ietf:password@foobar.yoyu.site:10xxx
```

但是相同协议链接 `ss://xxxx` 在 V2RayU 能够正常使用。对比 "Running Confg" 配置和V2RayU中代理配置，未见ss协议内容部分有区别。此外，若使用其他Shadowsocks客户端配置本地代理监听在1080，而Mellow使用此1080口Socks代理也能正常连接。

**Comment by laggardkernel** [comment]
@eycorsican 已查明是与DNS解析问题。这与我在本地搭建无污染的递归DNS有关。

我本地方式是 dnsmasq + chinadns + stubby 保证始终获得正确解析。经测试发现，Mellow 在建立连接阶段不会使用内部DNS，而是使用网卡接口上指定的DNS。也就说此时`hijack = Dns-Out`无效，后边的规则`[DnsServer]`不适用于建立ss连接阶段。

我本地网卡DNS设置为127.0.0.1，而dnsmasq监听在0.0.0.0上。虽然可以从dnsmasq日志中看到解析出了ss服务器对应的IP，但是Mellow好像没有拿到这个结果，或者是没有接受这个结果。把dnsmasq监听改为127.0.0.1后，问题就解决了。

dnsmasq监听在0.0.0.0上对于Mellow有什么影响吗？

**Comment by eycorsican** [comment]
视乎你整个方案配置细节的不同，请求过程可能会变得非常复杂，没配置啥都不好说。

**Comment by laggardkernel** [comment]
谢谢了。不过既然不是Mellow问题，我也不想更进一步研究了，知道如何避免这个问题就够了。
