### ISSUE TITLE
Mellow重载配置后在macOS菜单栏产生多余空白

### ISSUE THREAD

**Issue by laggardkernel** [mellow-io/mellow#55]
环境

- macOS 10.13.6
- Mellow v1.0.6

每次重载当前配置后，顶部菜单栏Mellow图标右侧产生多余空格。

**Comment by lieber68** [comment]
重载，切换配置好像都会产生多余空格

**Comment by eycorsican** [comment]
载个图来看下？10.15.1 没有这种问题，如果是低系统版本特定的问题，我大概没法修，没那环境。

**Comment by denyot** [comment]
> 载个图来看下？10.15.1 没有这种问题，如果是低系统版本特定的问题，我大概没法修，没那环境。

我也有同样的问题。如图所示，我的系统信息，和多余空格的展示。这些空格是 5 次重载留下的。
![image](https://user-images.githubusercontent.com/31619600/68300665-37a9ce80-00d9-11ea-96a3-c0a6564c42b8.png)

**Comment by lieber68** [comment]
<img width="161" alt="WechatIMG578" src="https://user-images.githubusercontent.com/17981721/68300757-6031c880-00d9-11ea-8444-544221acb2f3.png">
我用的10.15.1 mellow用0.1.8

**Comment by eycorsican** [comment]
重现不了不知道是什么问题。
