### ISSUE TITLE
mellow在ubuntu上无法使用

### ISSUE THREAD

**Issue by Aithosa** [mellow-io/mellow#58]
您好，我在ubuntu上尝试使用订阅链接来开启代理服务，但是下载`Mellow-0.1.7.AppImage`之后，放到ubuntu上运行时遇到一些问题：

1. 点击软件菜单上的about等选项后开启的框没有关闭按钮
![2019-10-25 (1)](https://user-images.githubusercontent.com/32020141/67560601-ca4b8480-f74d-11e9-9094-4ead6c78e2b4.png)

2. 添加订阅链接后，每一次类似操作(添加订阅链接/点击已存在的订阅链接)都会导致多开一个状态栏的图标
![2019-10-25](https://user-images.githubusercontent.com/32020141/67560526-a6883e80-f74d-11e9-8e55-fcf52b9c97e4.png)

3. 点击connect没有任何反应，并且此时如果不退出软件的话无法连接网络。
![2019-10-25 (2)](https://user-images.githubusercontent.com/32020141/67560739-1696c480-f74e-11e9-9ab4-27a12cf588e2.png)

希望可以得到一些帮助，是否是我进行了不当操作所造成的，我一开始是想在linux中开启代理然后作为网关来使用的，谢谢。

**Comment by gu18168** [comment]
manjaro 也是这个问题，问题一模一样

**Comment by hmilylmk** [comment]
> manjaro 也是这个问题，问题一模一样

请问有解决吗？小白求教

**Comment by N214** [comment]
Perppermint (Ubuntu 18.04) +1

**Comment by eycorsican** [comment]
最新版或许修复
