### ISSUE TITLE
希望增加睡眠唤醒后自动重连功能

### ISSUE THREAD

**Issue by vizshrc** [mellow-io/mellow#67]
每次唤醒都需要手动reconnect,感觉有些麻烦，希望作者大大考虑加入自动重连。昨天试用了surge，不知道它是怎么做的。对我而言，需要的只是一个代理工具，我觉得许多人也是如此，如果mellow的网络切换可以和surge一样顺滑，它的体验就不亚于surge。谢谢作者大大的努力，mellow已经很棒。Catalina10.15.1。

**Comment by eycorsican** [comment]
如果唤醒后不能自动重连，那就是 BUG，请提供日志。

**Comment by vizshrc** [comment]
由于我直接搬了以前编辑的v2ray的JSON配置文件（log是info），所以暂不能提供log,请允许我稍后上传，我使用Mellow文档的配置不知道怎么添加path /ray，我正解决它。

**Comment by vizshrc** [comment]
搞清了大大。是我自己的问题。已经正常啦。就是配置conf文件时，例子中
Proxy-1, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:443/v2?network=ws&tls=true
请教一下            "wsSettings": {
              "path": "/ray"
这个改怎么加到后面？谢谢
