### ISSUE TITLE
core不支持X64的openwrt

### ISSUE THREAD

**Issue by feng92f** [mellow-io/mellow#68]
在多个 openwrt for x86_64 上测试不能执行 core ，可能是因为openwrt缺库不支持32位。

**Comment by feng92f** [comment]
能否提供64位的core

**Comment by eycorsican** [comment]
https://github.com/mellow-io/mellow/blob/master/src/helper/linux/core

**Comment by feng92f** [comment]
@eycorsican  我用的是这个文件 

root@Openwrt:~/test# ll -h
drwxr-xr-x    2 root     root        3.4K Nov  6 20:31 ./
drwxr-xr-x    1 root     root        3.4K Nov  6 20:31 ../
-rw-r--r--    1 root     root       19.4M Nov  6 20:31 core-test
root@Openwrt:~/test# chmod +x core-test
root@Openwrt:~/test# ll
drwxr-xr-x    2 root     root          3488 Nov  6 20:31 ./
drwxr-xr-x    1 root     root          3488 Nov  6 20:31 ../
-rwxr-xr-x    1 root     root      20301992 Nov  6 20:31 core-test*
root@Openwrt:~/test# ./core-test
-ash: ./core-test: not found
root@Openwrt:~/test# uname -a
Linux Openwrt 4.19.75 #0 SMP Mon Sep 30 01:47:47 2019 x86_64 Openwrt-Koolshare

提示 not found  但文件就在那里，猜测是架构的问题，或者是openwrt缺库
我测试了好几个openwrt都这样 ，现在openwrt lede系列的都不支持32位的了

**Comment by eycorsican** [comment]
https://github.com/mellow-io/mellow/releases/download/v0.1.8/core-linux-amd64

**Comment by feng92f** [comment]
啊啊啊 原来是没看到 多谢🍺
