### ISSUE TITLE
开启mellow 之后，迅雷无法使用

### ISSUE THREAD

**Issue by denyot** [mellow-io/mellow#69]
当开启 mellow 配合 clashx 透明代理时，迅雷无法正常使用。clashx同配置下， 配合 Proxifier 透明代理时迅雷是可以正常下载并会员加速的，所以排除 clashx 这边规则的问题。  我无法确定我 mellow 这边是否配置正确，下面的截图是我的配置。另外我单独使用 mellow 时，迅雷也是无法使用的。规则主要是引用的神机规则，我的服务器是不禁用 BT 下载的。    希望指点一下，是我哪里的配置不对。或者说 mellow 本身禁用了迅雷？

![image](https://user-images.githubusercontent.com/31619600/68299544-db45af80-00d6-11ea-87d0-0f85c49fb52a.png)

**Comment by eycorsican** [comment]
建议你查看以前的 issue，相关问题已经回答过多次，我不打算重复说。

**Comment by denyot** [comment]
哦，谢谢！不好意思。

**Comment by denyot** [comment]
刚刚仔细阅读了相关issue，确实没找到类似的问题。我这边其它应用都是可以正常代理的，唯独迅雷有问题。 我无法确定是哪个是哪个设置引起的，找不到头绪，望指点一下，非常感谢🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: eycorsican <notifications@github.com&gt;
发送时间: 2019年11月6日 21:33
收件人: mellow-io/mellow <mellow@noreply.github.com&gt;
抄送: denyot <823300635@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[mellow-io/mellow] 开启mellow 之后，迅雷无法使用 (#69)




建议你查看以前的 issue，相关问题已经回答过多次，我不打算重复说。

**Comment by eycorsican** [comment]
检查 UDP

**Comment by denyot** [comment]
多谢！问题已解决
