### ISSUE TITLE
ICMP support

### ISSUE THREAD

**Issue by johnwigley** [mellow-io/mellow#70]
How does the ICMP support work, is that to just forward ICMP through a local outbound?
Is there any documentation that describes how it works?

Thanks

**Comment by eycorsican** [comment]
- They are forwarded to the dest directly, it's the default behaivor ([`-relayICMP`](https://github.com/mellow-io/mellow/blob/49f5b643e33421e5fb3591d204d46e144996e6f6/src/main.js#L389))
- Or reply locally (without specifying `-relayICMP`)

ICMP packets never go through a proxy server, none of those proxy protocols support this.
