### ISSUE TITLE
conf文件中，wss类型headers host转换有什么额外参数么？

### ISSUE THREAD

**Issue by KOP-XIAO** [mellow-io/mellow#72]
Hi，
手写json文件时，可以正常联通
```
        "wsSettings": {
          "headers": {
            "Host": "xxxxx"
          },
          "path": "/"
        }
```
但写conf时，按照示范例子写了 “network=ws&ws.host=xxx”  则会生成下面这无法联通的json
```
 "wsSettings": {
          "host": "xxxxx "
          "path": "/"
        }
```
尝试了&ws.headers.host 则会丢失host参数。
想问下此处的headers host该如何在conf中写入？

**Comment by xlighting2017** [comment]
V2ray 官方配置:
![image](https://user-images.githubusercontent.com/25970065/68384508-b7e03a80-0192-11ea-8a74-fa9229601f8b.png)

转换函数:
![image](https://user-images.githubusercontent.com/25970065/68384532-c4649300-0192-11ea-8cd1-d5b256b9a2da.png)

所以是 转化函数 没写对
