### ISSUE TITLE
udp和dns-out设置相关

### ISSUE THREAD

**Issue by ynotoony** [mellow-io/mellow#73]
钉钉传输文件时，会走dns-out，即使我设置了钉钉走direct也没用。
是不是udp的流量都是走dns-out的？
有没有办法可以解决呢？
以下为配置：
"dns": {
      "servers": [
        "localhost",
        "223.5.5.5",
        {
          "address": "8.8.8.8",
          "port": 53,
          "domains": [
            "geosite:geolocation-!cn"
          ]
        },
        "8.8.4.4"
      ],
      "clientIp": "114.114.114.114",
      "hosts": {
        "doubleclick.net": "127.0.0.1"
      }
    },
    "outbounds": [
      {
        "protocol": "freedom",
        "tag": "Direct",
        "settings": {
          "domainStrategy": "UseIP"
        }
      },
      {
        "protocol": "blackhole",
        "tag": "Reject"
      },
      {
        "protocol": "dns",
        "tag": "Dns-Out",
        "settings": {}
      },
      {
        "protocol": "vmess",
        "tag": "Proxy-2",
        "settings": {
          "vnext": [
            {
              "users": [
                {
                  "id": "5xxxx-xxxx-xxxxd"
                }
              ],
              "address": "1.1.1.1",
              "port": 12345
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        }
      }
    ],
    "routing": {
      "balancers": [
        {
          "tag": "MyGroup",
          "selector": [
            "Proxy-2"
          ],
          "strategy": "latency",
          "interval": 300,
          "timeout": 6,
          "totalMeasures": 3, 
          "delay": 1, 
          "tolerance": 300, 
          "probeTarget": "tls:www.google.com:443", 
          "probeContent": "HEAD / HTTP/1.1\r\n\r\n"
        }
      ],
      "rules": [
        {
          "type": "field",
          "outboundTag": "Dns-Out",
          "inboundTag": [
            "tun2socks"
          ],
          "network": "udp",
          "port": 53
        },
        {
          "type": "field",
          "outboundTag": "Reject",
          "domain": [
            "geosite:category-ads-all"
          ]
        },
        {
          "type": "field",
          "outboundTag": "Direct",
          "ip": [
            "223.5.5.5/32"
          ]
        },
        {
          "type": "field",
          "balancerTag": "MyGroup",
          "ip": [
            "8.8.8.8/32",
            "8.8.4.4/32"
          ]
        },
        {
          "type": "field",
          "outboundTag": "Direct",
          "domain": [
            "geosite:cn"
          ]
        },
        {
          "type": "field",
          "outboundTag": "Direct",
          "ip": [
            "geoip:cn",
            "geoip:private"
          ]
        },
        {
          "type": "field",
          "outboundTag": "Direct",
          "port": "123"
        },
        {
          "type": "field",
          "outboundTag": "Direct",
          "app": [
            "DingTalk"
          ]
        },
        {
          "type": "field",
          "balancerTag": "MyGroup",
          "ip": [
            "0.0.0.0/0",
            "::/0"
          ]
        }
      ],
      "domainStrategy": "IPIfNonMatch"
    }
  }

**Comment by ynotoony** [comment]
问题是这样的，现在所有的udp流量都是走dns-out，能不能设置某些udp的流量走direct呢？

**Comment by ynotoony** [comment]
![image](https://user-images.githubusercontent.com/20440468/68589945-3f49e880-04c8-11ea-9653-b317e8cf4fa0.png)
比如这两个流量，直接direct就可以了。
我设置了dingtalk的流量走direct，但是不管用。不知道哪里能设置。

**Comment by eycorsican** [comment]
可以用 JSON 配置，把 
```json
{
"type": "field",
"outboundTag": "Direct",
"app": [
"DingTalk"
]
},
```

放到第一条路由。

**Comment by ynotoony** [comment]
感谢🙏🏻。解决了。
