### ISSUE TITLE
windows版本preference里的auto launch似乎没什么用。原本的功能是干什么的？

### ISSUE THREAD

**Issue by ow1wo** [mellow-io/mellow#78]
勾选了auto launch也不会随windows启动。这个选项是用作随系统启动的吗？

现在我的方法是创建一个task schedule用来随系统启动。我就想问一下auto launch勾选后背后做了什么设置

**Comment by eycorsican** [comment]
这个选项在 Windows 上不生效。

**Comment by zhuzeitou** [comment]
Win7上是有效的其实（不确定是不是和UAC有关，没去深究），Win10上还是得靠计划任务来做开机启动

**Comment by eycorsican** [comment]
跟权限有关，自从加入 [这个改动](https://github.com/mellow-io/mellow/blob/394283c6970dd7a1cc123d1e83f976368698c643/package.json#L60) 后 Win10 就不生效了，我也不想深究。
