### ISSUE TITLE
UDP 丢包率测试问题

### ISSUE THREAD

**Issue by feng92f** [mellow-io/mellow#80]
使用工具
[UDP丢包率检查工具](https://github.com/wangyu-/UDPspeeder/wiki/UDP%E4%B8%A2%E5%8C%85%E7%8E%87%E5%92%8C%E5%BB%B6%E8%BF%9F%E6%B5%8B%E8%AF%95%E5%B7%A5%E5%85%B7)
测试方法：
1. 如上链接建立一个udp echo服务器
2. 在路由上部署mellow做透明代理
3. 在路由下的一个机器上进行UDP检测

调节参数：长度 160 ，时间200ms
测试结果：
Reply from 35.xx seq=24 time=148.03 ms
Request timed out
Reply from 35.xx seq=26 time=141.79 ms
Request timed out
Request timed out
Reply from 35.xx seq=29 time=136.87 ms
Request timed out
Reply from 35.xx seq=31 time=141.57 ms
Reply from 35.xx seq=32 time=150.55 ms
Request timed out
Reply from 35.xx seq=34 time=117.75 ms
Reply from 35.xx seq=35 time=158.96 ms
Request timed out
Reply from 35.xx seq=37 time=129.49 ms

--- ping statistics ---
54 packets transmitted, 47 received, 12.96% packet loss
rtt min/avg/max = 117.75/146.52/180.95 ms

对比ss-dir的UDP转发结果

41 packets transmitted, 41 received, 0.00% packet loss
rtt min/avg/max = 83.23/97.21/106.65 ms

**Comment by feng92f** [comment]
200ms 有点低会被QOS，改为1000ms 仍然丢包不低。
1000ms
--- ping statistics ---
18 packets transmitted, 14 received, 22.22% packet loss
rtt min/avg/max = 126.06/135.99/153.05 ms

**Comment by feng92f** [comment]
@eycorsican

**Comment by eycorsican** [comment]
我测试的结果：
```
udpping.py <server-ip> 4000 "LEN=160;INTERVAL=200"
...
...
...
--- ping statistics ---
59 packets transmitted, 59 received, 0.00% packet loss
rtt min/avg/max = 13.52/17.67/37.72 ms
```

ss 服务端版本：shadowsocks-libev 2.6.3 with mbed TLS 2.4.2

mellow core 版本：0.1.9

UDP echo server：`socat -v UDP-LISTEN:4000,fork PIPE`，跟 ss 同一服务器。

测试过 mellow 运行在 macOS 上和运行是路由器透明代理上的场景，结果都差不多，没丢包。

跟 v2ray-core 实现的 ss 相比，ss-libev/ss-redir 在发 UDP 包时会多一个 [QoS 设置](https://github.com/shadowsocks/shadowsocks-libev/blob/6d73201b9a4e39d5535978a17a8536bd32b9ca27/src/udprelay.c#L848)，我不太确定是不是 QoS 问题，因为我用的测试服务器延迟也很低，大概也不会有 QoS 影响。

**Comment by eycorsican** [comment]
但是你在前面的 issue 提到，ss-redir -> mellow -> ss-libev 这样就不会有丢包，所以也不应该是 QoS 问题。

**Comment by feng92f** [comment]
今天测试 0.19 发现这个测试不丢包了
游戏仍然提示2-5%的丢包，无论我服务器放在哪里都一样（日本香港国内），不过游戏体验没有卡顿，Apex流畅，PUBG不丢包。

**Comment by eycorsican** [comment]
可以测试一下 游戏 -> mellow -> ss-local -> ss-libev 这样的组合，配置效仿 [这里](https://github.com/mellow-io/mellow/issues/3#issuecomment-520197534)。

**Comment by feng92f** [comment]
@eycorsican 好的，我开始测试。先不说为啥丢包，通过多个机房的测试，我发现UDP丢包还挺高的，存在Qos（运营商限速，机房处理UDP攻击等），所以才会有UDP2Raw这样项目来处理丢包，用的还不少。我在配置的时候，发现虽然把几个服务器放在一个组里，但是没有相应的策略选出丢包少的点，速度快不一定就丢包少，比如国内服务器，觉得这里是可以优化的。

**Comment by feng92f** [comment]
1. 19PM Beijing ss-redir v3.2 chaca20
--- ping statistics ---
493 packets transmitted, 481 received, 2.43% packet loss
rtt min/avg/max = 70.92/84.25/132.39 ms

Apex 显示 2% - 4% 丢包

2. 19 30PM Beijing ss-local(v3.2 chacha20 socks) + mellow 
--- ping statistics ---
226 packets transmitted, 178 received, 21.24% packet loss
rtt min/avg/max = 76.88/86.25/105.27 ms

Apex 显示 4-6%
3. 20 PM mellow standalone
--- ping statistics ---
178 packets transmitted, 152 received, 14.61% packet loss
rtt min/avg/max = 104.65/131.29/154.92 ms

Apex 显示 12-18%丢包

**Comment by feng92f** [comment]
21PM ss-redir + udp2raw

--- ping statistics ---
1782 packets transmitted, 1732 received, 2.81% packet loss
rtt min/avg/max = 72.07/86.49/172.56 ms

Apex 显示 0-4%  丢包

**Comment by feng92f** [comment]
@eycorsican 我今天测试了联通4G路由，长城宽带和联通
发现走IPLC机房的话，mellow和redir数据一样。
直接连外面机房的话，mellow数据不如redir，应该是那个Qos Flag的作用。

**Comment by eycorsican** [comment]
那你再测下这个：https://github.com/mellow-io/mellow/releases/download/v0.1.9/core-linux-amd64-out-tos

对流量出去的接口（非 TUN）抓包过滤 UDP 可以看到发到 ss-libev 的加密流量设置了 tos flag 0x2e：

21:20:48.677154 IP (***tos 0x2e,ECT(0)***, ttl 64, id 1536...


对比没有 tos flag 的：

21:20:38.603946 IP (***tos 0x0***, ttl 64, id 1083...

**Comment by feng92f** [comment]
![Snip20191116_20](https://user-images.githubusercontent.com/618440/68988212-b7b8fc80-086e-11ea-95bb-740827289ca4.png)
还是有区别，红色之前是mellow，切换后为redir
同样的服务器和加密方式，非IPLC。
