### ISSUE TITLE
使用fake dns后，UDP无法工作

### ISSUE THREAD

**Issue by a86913179** [mellow-io/mellow#82]
UDP请求被解析成fake ip后发送到tun，mellow没有反推域名用内置DNS解析再匹配规则，而是直接向fake ip请求，导致UDP只有发出，没有接收

如果我的理解没错的话，开启fake dns，TCP请求是会用fake ip反推域名用内置DNS解析IP匹配规则，假设规则是：
geoip,cn,direct
final,proxy
内置DNS解析出国内IP走直连，国外IP再将域名和数据发给PROXY

**Comment by eycorsican** [comment]
你想表达什么？

> 使用fake dns后，UDP无法工作

这个说法是肯定不对的。

**Comment by a86913179** [comment]
> 你想表达什么？
> 
> > 使用fake dns后，UDP无法工作
> 
> 这个说法是肯定不对的。

就是带域名的UDP请求无法发送到公网，纯IP的UDP请求没问题

**Comment by a86913179** [comment]
单独用domain sniffing没问题，单独用fake dns的情况下，mellow规则设置qbittorrent直连，打开qbittorrent，所有使用域名的udp tracker显示失败，tracker使用的是https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt，如果使用纯ip的udp tracker则正常。但是很奇怪DHT bootstrap节点也是带域名的UDP请求，却可以更新。还有chrome的UDP也是发送几百字节，接收0字节。

**Comment by eycorsican** [comment]
> 打开qbittorrent，所有使用域名的udp tracker显示失败

> 还有chrome的UDP也是发送几百字节，接收0字节。

原则上不能根据这些来判断问题，前者或许是因为网络路径变了导致没返回，后者 chrome 的一些 UDP 本来就是用来做网络发现的，没返回正常。

当然也不排除是真的有问题，但如果不给出一个可以稳定复现的方法，我不打算仔细去看这个问题。

**Comment by a86913179** [comment]
> > 打开qbittorrent，所有使用域名的udp tracker显示失败
> 
> > 还有chrome的UDP也是发送几百字节，接收0字节。
> 
> 原则上不能根据这些来判断问题，前者或许是因为网络路径变了导致没返回，后者 chrome 的一些 UDP 本来就是用来做网络发现的，没返回正常。
> 
> 当然也不排除是真的有问题，但如果不给出一个可以稳定复现的方法，我不打算仔细去看这个问题。

行吧。那close了
