### ISSUE TITLE
dns泄露问题

### ISSUE THREAD

**Issue by YanpengGu** [mellow-io/mellow#83]
全局模式在win10环境下会发生dns泄露，win7则不会。
另外，可否将初始的mellow-tap的dns 223.5.5.5 1.1.1.1改为1.1.1.1 8.8.8.8。
感谢。

**Comment by ow1wo** [comment]
没错。我用dnscrypt做dns服务器，比223.5.5.5速度都好，但是发现即使设置全局代理，dns还是去访问223.5.5.5。日本节点访问国内网站也不慢，对于我根本没必要dns分流。但是貌似TAP里的dns才是默认的dns服务器，而TAP重启进程后就被重置了，每次都要去设，非常烦

**Comment by eycorsican** [comment]
#84
