### ISSUE TITLE
windows版本能否修改TAP网卡默认的dns？223.5.5.5会丢包，延时70+ms，比到日本的vps还差

### ISSUE THREAD

**Issue by ow1wo** [mellow-io/mellow#84]
手动修改TAP网卡的dns设置会在重启mellow时被重置。能在配置中设置TAP的DNS吗？223.5.5.5可能并不适合所有人，要是能有地方修改下就好了

**Comment by a86913179** [comment]
网卡设置什么DNS都不重要，最终都会被劫持到mellow，由内置DNS解析，我想你还没搞到这个软件的原理

**Comment by ow1wo** [comment]
> 网卡设置什么DNS都不重要，最终都会被劫持到mellow，由内置DNS解析，我想你还没搞到这个软件的原理

我配置全局代理也会用内置dns吗？
基本上我的配置文件就一行，类似下面的：
[Endpoint]
MyProxyServer, ss, ss://aes-128-gcm:pass@192.168.100.1:8888
v2ray的json配置文件就一个outbound，我不认为这样会劫持dns。软件作者写的漫谈dns在代理环境中的使用一文我是读过的，对这个软件原理略知一二。

我使用dnscrypt来防投毒，因此不希望劫持我的dns，希望用默认的dns服务器

**Comment by a86913179** [comment]
劫持不劫持不是看outbound的，而是看routing，默认的conf配置是劫持所有发到tun的UDP53端口流量，通过runing-config.json可以看到routing有条规则inboundtag是tun2socks，outbound是dns-out的

如果你用的是json，那么默认配置里是没有劫持的，还有fake dns的劫持UDP53不是写在配置里的，而是直接写在代码里的，无法改变

**Comment by ow1wo** [comment]
全局代理没有你说的routing，就一个outbound，dns并没有被劫持，而是用tap网卡配置的dns地址走正常的dns解析流程。
tap网卡的默认地址写在main.js里，我正尝试自己编译一个安装包暂时自己用。提这个issue的目的是希望作者能提供一个配置tap网卡的选项，这样不用每次重启进程时再去设置一遍虚拟网卡的dns

**Comment by eycorsican** [comment]
@ow1wo 配置一下 dns hijack，然后想用什么 dns 就写到 [DnsServer] 里：

```ini
[Endpoint]
MyProxyServer, ss, ss://aes-128-gcm:pass@192.168.100.1:8888
dns-out, builtin, dns

[Dns]
hijack = dns-out

[DnsServer]
1.1.1.1
8.8.8.8
```

**Comment by ow1wo** [comment]
> @ow1wo 配置一下 dns hijack，然后想用什么 dns 就写到 [DnsServer] 里：
>
昨天我是配了dns hijack的，但是发现dns解析很慢，有时解析不到。可能昨天是vps线路问题，今天重配后又稳定了
