### ISSUE TITLE
Windows 上运行 Mellow 仍会导致 DNS 泄露

### ISSUE THREAD

**Issue by shunf4** [mellow-io/mellow#88]
如题，Windows 在查询 DNS 的时候似乎会在每一个网络接口上配置的 DNS 都查询一次，而不管这个网络接口是不是路由表指定的默认网关所在。这样 `nslookup somehost.com`、`ssh somehost.com` 会造成 DNS 泄露（如向以太网配置的 DHCP DNS 查询 DNS，而这肯定不会经由 TAP），且有拿到 DNS 污染后的 IP 地址的风险。

而如果用把其他适配器的 DNS 设定为 `10.255.0.1` 再用 dokodemo-door 协议的方法， ~~一方面可能造成内置 DNS 配置中 `"dns.servers": ["localhost"]` 不起作用，一方面每次开关 Mellow 都要去设置一下比较麻烦。~~ 将会引起 DNS 查询严重超时，因为对 10.255.0.1 的查询会在*那个*适配器发出，而不是从 TAP。

是否可以参考 OpenVPN 的 `block-outside-dns` 选项的实现： https://community.openvpn.net/openvpn/ticket/605 来解决这个问题？

另外也可以考虑把添加默认路由的方式从 `0.0.0.0/0` 变为 `0.0.0.0/1 + 128.0.0.0/1`，类似于 OpenVPN 的 `redirect-gateway def1`。这样就不用记住之前的默认路由了。

**Comment by YanpengGu** [comment]
我也发现了这个问题，但是仅限win10，win7没有这个问题。

**Comment by comindap** [comment]
Windows 10 1909同样复现，而且Fake DNS功能在这种情况下失效。需要注意，IPv6开启的情况下，情况可能会更复杂一些。
我目前的解决方案是用其它DoH类应用（例如AuroraDNS）来防止DNS泄露。但是这样一来，Fake DNS功能被彻底绕过。
感谢作者

**Comment by eycorsican** [comment]
可以确认一下 https://community.openvpn.net/openvpn/ticket/605#comment:25 中提到的方法可以在 Mellow 中解决这个问题吗？即把 mellow-tap0 适配器的 metric 调低，做法参考这里：https://superuser.com/questions/966832/windows-10-dns-resolution-via-vpn-connection-not-working

**Comment by YanpengGu** [comment]
> 可以确认一下 https://community.openvpn.net/openvpn/ticket/605#comment:25 中提到的方法可以在 Mellow 中解决这个问题吗？即把 mellow-tap0 适配器的 metric 调低，做法参考这里：https://superuser.com/questions/966832/windows-10-dns-resolution-via-vpn-connection-not-working
> 
> 如果可以的话还是很好修的，在这个脚本后面加条命令就可以：https://github.com/mellow-io/mellow/blob/master/src/helper/win32/ensure_tap_device.bat

测试失败，mellow-tap跃点数设为1，其余适配器设为10，依旧dns泄露。

**Comment by eycorsican** [comment]
@YanpengGu 

IPv6 也设 metric 了？

https://superuser.com/questions/966832/windows-10-dns-resolution-via-vpn-connection-not-working 中有条评论：

> This fixed the issue for us (and we've been battling it for some time), with one important additional step -- disabling IPv6. Our VPN does not do IPv6 but my understanding is any IPv6 resolver will take precedent over IPv4 ones. Once we disabled IPv6 on the adapters then adjusted the metrics split-tunnel DNS resumed working. If your VPN supports IPv6 this is likely not needed and if the metric adjustment by itself fixes DNS for you keep IPv6 enabled on your adapter.

**Comment by YanpengGu** [comment]
> @YanpengGu
> 
> IPv6 也设 metric 了？
> 
> https://superuser.com/questions/966832/windows-10-dns-resolution-via-vpn-connection-not-working 中有条评论：
> 
> > This fixed the issue for us (and we've been battling it for some time), with one important additional step -- disabling IPv6. Our VPN does not do IPv6 but my understanding is any IPv6 resolver will take precedent over IPv4 ones. Once we disabled IPv6 on the adapters then adjusted the metrics split-tunnel DNS resumed working. If your VPN supports IPv6 this is likely not needed and if the metric adjustment by itself fixes DNS for you keep IPv6 enabled on your adapter.

对，ipv6 ipv4都设置了

**Comment by a86913179** [comment]
win10的问题，改跃点之后，把网卡适配器属性里的IPV6也给关了，IPV6本身就不走tun2socks，不关的话DNS会走IPV6

Smart multi-homed name resolution is a DNS related feature that Microsoft introduced in Windows 8 and implemented in Windows 10 as well.

https://www.ghacks.net/2017/08/14/turn-off-smart-multi-homed-name-resolution-in-windows/

**Comment by YanpengGu** [comment]
> win10的问题，改跃点之后，把网卡适配器属性里的IPV6也给关了，IPV6本身就不走tun2socks，不关的话DNS会走IPV6
> 
> Smart multi-homed name resolution is a DNS related feature that Microsoft introduced in Windows 8 and implemented in Windows 10 as well.
> 
> https://www.ghacks.net/2017/08/14/turn-off-smart-multi-homed-name-resolution-in-windows/

可是我关闭了所有适配器的ipv6依旧dns泄露啊。

**Comment by shunf4** [comment]
我在 Windows 10 1909 18363.418 上，以太网适配器有 IPv4 和 IPv6 地址且都是自动跃点，mellow-tap 设 IPv4 跃点为 3 （IPv6 保持默认关闭）后一切正常了，用 Wireshark 看到所有的 DNS 请求都只对 223.5.5.5 从 mellow-tap 发出，mellow-tap 也给予了正确的回应

不正常的可以试试我这个 Windows 版本？

**Comment by shunf4** [comment]
并没有一切正常，只有 nslookup 不泄露，调用 `gethostbyname` 系统函数如

```ipconfig /flushdns & python -c "import socket;print(socket.gethostbyname('somehost.com'))"```

还是可以观察到从以太网适配器出去的 DNS 查询（有 IPv6 优先 IPv6，如果 IPv6 关了就用 IPv4），不过这并没有影响查询结果，查询结果仍是 Mellow 给的正确结果。

**Comment by eycorsican** [comment]
@shunf4 你在以太网适配器上观察到的 DNS 查询会不会是 Mellow 发出的？

**Comment by eycorsican** [comment]
在 outline 那边找到了些相关的讨论：

https://github.com/Jigsaw-Code/outline-client/issues/191
https://github.com/Jigsaw-Code/outline-client/pull/394

似乎还是用 WFP 来解决比较好，我得找个时间看看能不能在 Go 中调用 WFP 来实现。

**Comment by eycorsican** [comment]
v0.1.11 应该已经修好。

**Comment by YanpengGu** [comment]
> v0.1.11 应该已经修好。

感谢，测试有效。

**Comment by eycorsican** [comment]
FYI

v0.1.11 使用了 WFP 来解决这个问题，具体来说，按优先级从高到低加入以下 WFP 规则：
