### ISSUE TITLE
[Enhancement] 考虑用Systray替换掉Electron

### ISSUE THREAD

**Issue by steveqx** [mellow-io/mellow#96]
现有用Electron主要是为了菜单栏，可以考虑用systray，轻量很多。
https://github.com/getlantern/systray
a cross platfrom Go library to place an icon and menu in the notification area

**Comment by eycorsican** [comment]
这个 systray 项目是不可能考虑的，太小众功能太单一。

类似项目可以考虑 go-flutter: https://github.com/go-flutter-desktop/go-flutter ，也并非一定要做成 tray 菜单，主要是现在我不会写 UI（也不想写），所以用 tray 做了个最基本的交互。
