### ISSUE TITLE
Mellow 启动时会导致 VSCode 的 Remote-WSL 关闭

### ISSUE THREAD

**Issue by redblue9771** [mellow-io/mellow#98]
Mellow 启动时会导致 WSL 关闭，怎么把 WSL2 的 IP 过滤掉？

**Comment by eycorsican** [comment]
测试过 0.1.10 吗？

**Comment by redblue9771** [comment]
@eycorsican 是 0.1.10，严格的说这个不是 Mellow 导致的问题，因为 WSL2 是真正的虚拟机，靠 TAP 与 Windows 取得通信，但是我不是很清楚，在使用 WSL2 做开发的时候使用 Mellow 全局代理要怎样才能把它过滤掉，或者说是 DNS 到正确的地方？

**Comment by eycorsican** [comment]
WSL 我测过 0.1.11 没问题，0.1.10 应该也不会有问题。

要提醒下的是 WSL 里面的系统的 DNS 不能是私有地址或 search lan 之类的，跟在真实 Linux 上配置注意事项差不多，具体看 readme。

另外 WSL 里发出的流量除了没有 process name 外，其它分流规则都可以用，跟 Windows 本机流量没什么区别。

**Comment by redblue9771** [comment]
不好意思，我可能没有描述清楚。具体来说是会中断 VSCode 的远程模式。

WSL2：Ubuntu
VSCode：最新稳定版
WIn: 19033.1
